(function(){
"use strict";
function unknown(){return{state:"NICHT VERFÜGBAR",tone:"unknown",value:"Nicht von der Live-API geliefert"};}
function valid(key,value,unit,digits,fault){return function(s){if(s[key]===null)return unknown();if(s[key]===false&&fault&&s.fault===fault)return{state:"FEHLER",tone:"fault",value:s.fault_description};var number=Number(s[value]);return{state:s[key]?"LIVE":"NICHT ANGESCHLOSSEN",tone:s[key]?"valid":"neutral",value:s[key]&&Number.isFinite(number)?number.toFixed(digits===undefined?1:digits).replace(".",",")+" "+unit:"—"};};}
function detected(key,value){return function(s){if(s[key]===null)return unknown();return{state:s[key]?"LIVE":"NICHT ANGESCHLOSSEN",tone:s[key]?"detected":"neutral",value:s[key]&&value?value(s):"—"};};}
function observed(value){return{state:"LIVE",tone:"configured",value:value||"Nicht direkt überwacht"};}
function part(id,name,short,group,role,signal,connection,pin,live){return{id:id,name:name,short:short,group:group,role:role,signal:signal,connection:connection,pin:pin,configured:true,live:live};}
window.V4_COMPONENTS=[
 part("cup","Becher / Aufnahme","Becher","physical","Der tief eingesetzte Becher drückt seitlich einen mechanischen Schalter mit langem flachem Taststößel; GP13 wertet dessen Signal aus.","S_DETECT","Mechanischer Langtaster · seitliche Bechererkennung","GP13",function(s){if(s.cup===null)return unknown();return{state:"LIVE",tone:"detected",value:s.cup?"Schalter gedrückt · Becher vorhanden":"Schalter frei · kein Becher"};}),
 part("temp1","TMP36 Sensor 1","Sensor 1","sensors","TO-92-Temperaturfühler oben seitlich am Becher; liefert den primären Istwert y(t).","TEMP_1_ADC","TMP36 → Pico ADC","GP26 / ADC0",valid("temp1_ok","temperature1","°C",1,"TEMPERATURSENSOR")),
 part("temp2","TMP36 Sensor 2","Sensor 2","sensors","Zweiter TO-92-Fühler mit Federkontakt direkt mittig unter dem Becher.","TEMP_2_ADC","TMP36 → TLA2024 AIN3","AIN3",valid("temp2_ok","temperature2","°C",1)),
 part("plate","Untere Temperaturplatte","Kontaktplatte","thermal","Metallische Auflage für Becherboden, Bechererkennung und die untere Temperaturmessung.","Thermische Kopplung","Becherboden ↔ Metallplatte","Mechanisch",function(s){return observed(s.power>0?"Wärmeverteilung aktiv":"Keine aktive Heizleistung");}),
 part("peltier1","Peltier-Heizung 1","Peltier 1","power","Dünnes keramisches Heizmodul links am Becher; eine Metallbacke überträgt Wärme seitlich in die Aufnahme.","PEL1_PWM / INA / INB / SEL","Pico W → VNH7070 → Peltier links","GP17–GP20",function(s){if(!s.power_supplied)return unknown();return{state:s.power>0?"LIVE":"ANGESCHLOSSEN",tone:s.power>0?"active":"configured",value:s.power>0?s.power.toFixed(0)+" % · "+(s.current1_ok?s.current1.toFixed(2)+" A":"Strom nicht verfügbar"):"Ausgang sicher aus"};}),
 part("peltier2","Peltier-Heizung 2","Peltier 2","power","Dünnes keramisches Heizmodul rechts am Becher; zweite symmetrische thermische Kontaktbacke.","PEL2_PWM / INA / INB / SEL","Pico W → VNH7070 → Peltier rechts","GP21 / GP22 / GP27 / GP28",function(s){if(!s.power_supplied)return unknown();return{state:s.power>0?"LIVE":"ANGESCHLOSSEN",tone:s.power>0?"active":"configured",value:s.power>0?s.power.toFixed(0)+" % · "+(s.current2_ok?s.current2.toFixed(2)+" A":"Strom nicht verfügbar"):"Ausgang sicher aus"};}),
 part("fan","4-Pin PWM-Lüfter","Lüfter","thermal","Genau ein gerahmter Lüfter sitzt innen unter dem Becher; PWM regelt, Tacho überwacht die Drehzahl.","FAN_PWM / FAN_TACHO / FAN_CTRL","Pico W ↔ 4-Pin-Lüfter","GP14 / GP15 / GP16",function(s){if(s.fault==="LUEFTER")return{state:"FEHLER",tone:"fault",value:"Tachosignal unplausibel"};if(!s.fan_supplied)return unknown();return{state:"LIVE",tone:s.fan_rpm>0?"active":"configured",value:s.fan_rpm>0?s.fan_rpm.toFixed(0)+" rpm":"Stillstand"};}),
 part("pico","Raspberry Pi Pico W","Pico W","control","Zentrale Recheneinheit für PI-Regelung, Zustandsautomat, Safety, WLAN und Webserver.","GPIO / ADC / I²C / WLAN","Auf der Hauptleiterplatte","RP2040",function(s,online){return online?{state:"LIVE",tone:"detected",value:"API über "+s.wifi_ip}:unknown();}),
 part("adc","TLA2024","TLA2024","sensors","Externer 4-Kanal-ADC für beide Strommessungen, Lichtsensor und TMP36 #2.","I2C_DATA / I2C_CLOCK","AIN0–AIN3 ↔ I²C0","GP0 / GP1 · 0x48",detected("tla2024_ok",function(){return"I²C-ADC verfügbar";})),
 part("current1","Strommessung Peltier 1","Strom P1","sensors","Überwacht den elektrischen Strom im ersten Peltier-Leistungspfad.","PEL1_CS","VNH7070 → TLA2024 AIN0","AIN0",valid("current1_ok","current1","A",2)),
 part("current2","Strommessung Peltier 2","Strom P2","sensors","Überwacht den elektrischen Strom im zweiten Peltier-Leistungspfad.","PEL2_CS","VNH7070 → TLA2024 AIN1","AIN1",valid("current2_ok","current2","A",2)),
 part("light","Lichtsensor","Licht","auxiliary","Der reale optische Sensor sitzt unten hinter einem eigenen Lichtfenster und regelt nur Display- und Statushelligkeit.","LIGHT_ADC","Optischer Sensor → TLA2024 AIN2","AIN2",function(s){if(s.light_ok===null)return unknown();return s.light_ok?{state:"LIVE",tone:"valid",value:Math.round(s.light_level*100)+" % · "+(s.night?"Nachtmodus":"Tagmodus")}:{state:"NICHT ANGESCHLOSSEN",tone:"neutral",value:"—"};}),
 part("oled","SSD1306 OLED","Display","interface","Physisch integriertes 128×64-OLED für Temperatur, Zustand, Leistung sowie WLAN-IP.","I²C","I²C0 ↔ OLED","GP0 / GP1 · 0x3C",detected("display_initialized",function(){return"Display initialisiert";})),
 part("rgb","RGB-Statusring","RGB-Ring","interface","Zwölf dezente RGB-Pixel im oberen Haltering zeigen den Gesamtzustand.","RGB_DIN","Pico W → WS2812-Ring","GP8",function(){return observed("Nicht direkt überwacht");}),
 part("leds","Status-LEDs","Status-LEDs","interface","Fünf kleine reale LEDs auf der Bedien- beziehungsweise Leiterplattenfläche zeigen READY, HEATING, HOLDING, Webserver und Fehler.","OUT_LED1_n … FB_LED_n","Active-low GPIO-Ausgänge","GP2–GP6",function(){return observed("Nicht direkt überwacht");}),
 part("buttons","Bedientaster","Taster","interface","Vier physische Taster MODE, DOWN, OK und UP an der Frontbedienung.","S_MODE / S_DOWN / S_OK / S_UP","Taster → Pico W","GP9–GP12",function(){return observed("Nicht direkt überwacht");}),
 part("power","12-V-Leistungsanschluss","Power","power","Seitlicher 12-V-Anschluss und überwachte 5-V-Logikfreigabe; fehlendes Power-Good sperrt START.","PG_5V0","12 V → Leistungsstufe / 5 V Logik","GP7",function(s){if(s.power_good===null)return unknown();return s.power_good?{state:"LIVE",tone:"detected",value:"Power Good aktiv"}:{state:"NICHT ANGESCHLOSSEN",tone:"neutral",value:"Leistungspfad nicht freigegeben"};}),
 part("wifi","WLAN Client","WLAN","connectivity","Der Pico W verbindet sich als Client mit dem Präsentations-Hotspot und erhält seine IP per DHCP.","CYW43 / DHCP","Pico W ↔ WLAN-Hotspot","2,4 GHz",function(s){if(s.wifi===null)return unknown();return s.wifi?{state:"LIVE",tone:"detected",value:s.wifi_ssid+" · "+s.wifi_ip}:{state:"NICHT ANGESCHLOSSEN",tone:"neutral",value:"WLAN getrennt"};}),
 part("webserver","HTTP-Webserver","Webserver","connectivity","Liefert Dashboard und API als offlinefähige Single Page direkt aus dem Pico-Flash.","HTTP / TCP","Port 80 über DHCP-IP","lwIP Raw API",detected("webserver_ready",function(){return"HTTP bereit";}))
];
})();
