(function(){
"use strict";
function unknown(){return{state:"NICHT VERFÜGBAR",tone:"unknown",value:"Nicht von der Live-API geliefert"};}
function valid(key,value,unit,digits){return function(s){var supplied=s[key];if(supplied===null)return unknown();var number=Number(s[value]);return{state:supplied?"MESSUNG GÜLTIG":"NICHT ERKANNT",tone:supplied?"valid":"neutral",value:supplied&&Number.isFinite(number)?number.toFixed(digits===undefined?1:digits).replace(".",",")+" "+unit:"—"};};}
function detected(key,value){return function(s){var supplied=s[key];if(supplied===null)return unknown();return{state:supplied?"ERKANNT":"NICHT ERKANNT",tone:supplied?"detected":"neutral",value:supplied&&value?value(s):"—"};};}
function inferred(state,value,tone){return{state:state,tone:tone||"configured",value:value||"Kein separater Discovery-Kanal"};}
window.V4_COMPONENTS=[
 {id:"cup",name:"Becher / Aufnahme",short:"Bechererkennung",group:"physical",position:[56,39],anchor:[.72,.05,.53],explode:[0,.08,0],role:"Thermische Regelstrecke mit mechanischer Bechererkennung",signal:"S_DETECT",connection:"GP13 · digitale Bechererkennung",pin:"GP13",configured:true,live:function(s){return detected("cup",function(){return"Becher vorhanden";})(s);}},
 {id:"temp1",name:"TMP36 Sensor 1",short:"Sensor 1",group:"sensors",position:[65,42],anchor:[1.00,.34,.12],explode:[.32,.28,0],role:"Erfasst den Istwert y(t) am Becherboden und an der Kontaktplatte",signal:"TEMP_1_ADC",connection:"Analoge Messung zum Pico W",pin:"GP26 / ADC0",configured:true,live:valid("temp1_ok","temperature1","°C",1)},
 {id:"temp2",name:"TMP36 Sensor 2",short:"Sensor 2",group:"sensors",position:[38,31],anchor:[-.78,1.10,.64],explode:[-.30,.62,0],role:"Erfasst den zweiten Temperaturwert seitlich am Becher",signal:"TEMP_2_ADC",connection:"TLA2024 AIN3 → I²C → Pico W",pin:"AIN3",configured:true,live:valid("temp2_ok","temperature2","°C",1)},
 {id:"plate",name:"Heizplatte",short:"Heizplatte",group:"thermal",position:[50,57],anchor:[0,-.02,.82],explode:[0,-.16,0],role:"Überträgt den Wärmeeintrag direkt auf den Becherboden",signal:"Thermische Kopplung",connection:"Peltier → Platte → Becher",pin:"Mechanisch",configured:true,live:function(s){if(!s.power_supplied)return unknown();return inferred(s.power>0?"AKTIV":"VORGESEHEN",s.power>0?s.power.toFixed(0)+" % Wärmeeintrag":"Wärmeweg inaktiv",s.power>0?"active":"configured");}},
 {id:"peltier1",name:"Peltier-Heizung 1",short:"Peltier 1",group:"power",position:[45,64],anchor:[-.51,-.32,.58],explode:[0,-.50,0],role:"Erster ausschließlich in Heizrichtung betriebener Aktorkanal",signal:"PEL1_PWM / INA / INB / SEL",connection:"Pico W → VNH7070 → Peltier 1",pin:"GP17–GP20",configured:true,live:function(s){if(!s.power_supplied)return unknown();var current=s.current1_ok===true?" · "+s.current1.toFixed(2)+" A":" · Strom nicht verfügbar";return inferred(s.power>0?"AKTIV":"VORGESEHEN",s.power>0?s.power.toFixed(0)+" %"+current:"Ausgang sicher aus",s.power>0?"active":"configured");}},
 {id:"peltier2",name:"Peltier-Heizung 2",short:"Peltier 2",group:"power",position:[55,64],anchor:[.51,-.32,.58],explode:[0,-.50,0],role:"Zweiter parallel geregelter Heizkanal",signal:"PEL2_PWM / INA / INB / SEL",connection:"Pico W → VNH7070 → Peltier 2",pin:"GP21 / GP22 / GP27 / GP28",configured:true,live:function(s){if(!s.power_supplied)return unknown();var current=s.current2_ok===true?" · "+s.current2.toFixed(2)+" A":" · Strom nicht verfügbar";return inferred(s.power>0?"AKTIV":"VORGESEHEN",s.power>0?s.power.toFixed(0)+" %"+current:"Ausgang sicher aus",s.power>0?"active":"configured");}},
 {id:"fan",name:"4-Pin PWM-Lüfter",short:"Lüfter",group:"thermal",position:[50,80],anchor:[0,-.98,.90],explode:[0,-1.15,.18],role:"Führt Wärme auf der kalten Peltier-Seite kontrolliert ab",signal:"FAN_PWM / FAN_TACHO / FAN_CTRL",connection:"Pico W ↔ Lüfter",pin:"GP14 / GP15 / GP16",configured:true,live:function(s){if(s.fault==="LUEFTER")return{state:"FEHLER",tone:"fault",value:"Tachosignal unplausibel"};if(!s.fan_supplied)return unknown();return s.fan_rpm>0?{state:"AKTIV",tone:"active",value:s.fan_rpm.toFixed(0)+" rpm"}:inferred("VORGESEHEN","Stillstand · Tacho nicht bewertbar");}},
 {id:"pico",name:"Raspberry Pi Pico W",short:"Pico W",group:"control",position:[31,64],anchor:[-1.54,-.25,.16],explode:[-.72,-.20,0],role:"Regelung, Zustandsautomat, Sicherheit, WLAN und Webserver",signal:"PI-Regler / GPIO / ADC / I²C",connection:"Zentrale Recheneinheit",pin:"RP2040",configured:true,live:function(s,online){return online?{state:"ERKANNT",tone:"detected",value:"Live-API · "+s.wifi_ip}:{state:"NICHT VERFÜGBAR",tone:"neutral",value:"Keine Live-Verbindung"};}},
 {id:"adc",name:"TLA2024",short:"TLA2024",group:"sensors",position:[35,69],anchor:[-1.24,-.16,.16],explode:[-.72,-.20,0],role:"Externer 4-Kanal-ADC für Strom, Licht und Sensor 2",signal:"I2C_DATA / I2C_CLOCK",connection:"AIN0–AIN3 ↔ I²C0 ↔ Pico W",pin:"GP0 / GP1 · 0x48",configured:true,live:detected("tla2024_ok",function(){return"I²C-ADC verfügbar";})},
 {id:"current1",name:"Peltier-Strommessung 1",short:"Strom P1",group:"sensors",position:[34,72],anchor:[-1.23,-.46,.16],explode:[-.72,-.20,0],role:"Überwacht den Strom des ersten Heizkanals",signal:"PEL1_CS",connection:"VNH7070 → TLA2024 AIN0",pin:"AIN0",configured:true,live:valid("current1_ok","current1","A",2)},
 {id:"current2",name:"Peltier-Strommessung 2",short:"Strom P2",group:"sensors",position:[39,74],anchor:[-1.55,-.46,.16],explode:[-.72,-.20,0],role:"Überwacht den Strom des zweiten Heizkanals",signal:"PEL2_CS",connection:"VNH7070 → TLA2024 AIN1",pin:"AIN1",configured:true,live:valid("current2_ok","current2","A",2)},
 {id:"light",name:"Lichtsensor",short:"Licht",group:"auxiliary",position:[68,72],anchor:[1.64,-.51,.21],explode:[.58,-.12,0],role:"Steuert ausschließlich Anzeigehelligkeit und Nachtmodus",signal:"LIGHT_ADC",connection:"Sensor → TLA2024 AIN2",pin:"AIN2",configured:true,live:function(s){if(s.light_ok===null)return unknown();return s.light_ok?{state:"MESSUNG GÜLTIG",tone:"valid",value:Math.round(s.light_level*100)+" % · "+(s.night===true?"Nachtmodus":"Tagmodus")}:{state:"NICHT ERKANNT",tone:"neutral",value:"—"};}},
 {id:"oled",name:"SSD1306 OLED",short:"Display",group:"interface",position:[67,62],anchor:[1.38,-.12,.21],explode:[.58,-.12,0],role:"Lokale Anzeige für Temperatur, Zustand, Leistung, WLAN und IP",signal:"I²C",connection:"I²C0 ↔ OLED 128×64",pin:"GP0 / GP1 · 0x3C",configured:true,live:detected("display_initialized",function(){return"Display initialisiert";})},
 {id:"rgb",name:"RGB-Statusring",short:"RGB-Ring",group:"interface",position:[57,55],anchor:[.90,-.01,.66],explode:[0,-.16,0],role:"Weithin sichtbare Gesamtzustandsanzeige mit 12 Pixeln",signal:"RGB_DIN",connection:"Pico W → WS2812-Ring",pin:"GP8",configured:true,live:function(){return{state:"NICHT DIREKT ÜBERWACHT",tone:"unknown",value:"Konfigurierter Statusausgang"};}},
 {id:"leds",name:"Status-LEDs",short:"Status-LEDs",group:"interface",position:[68,66],anchor:[1.22,-.38,.21],explode:[.58,-.12,0],role:"READY, HEATING, HOLDING, Webserver und Fehlerstatus",signal:"OUT_LED1_n … FB_LED_n",connection:"Active-low GPIO-Ausgänge",pin:"GP2–GP6",configured:true,live:function(){return{state:"NICHT DIREKT ÜBERWACHT",tone:"unknown",value:"Physischer LED-Zustand nicht rückgelesen"};}},
 {id:"buttons",name:"Bedientaster",short:"Buttons",group:"interface",position:[63,68],anchor:[1.38,-.38,.21],explode:[.58,-.12,0],role:"MODE, DOWN, OK und UP für lokale Bedienung",signal:"S_MODE / S_DOWN / S_OK / S_UP",connection:"Taster → Pico W",pin:"GP9–GP12",configured:true,live:function(){return{state:"NICHT DIREKT ÜBERWACHT",tone:"unknown",value:"Tasterzustand wird nicht publiziert"};}},
 {id:"power",name:"Leistungsversorgung",short:"Power",group:"power",position:[28,76],anchor:[-1.79,-.60,.16],explode:[-.72,-.20,0],role:"12-V-Leistung und geprüfte 5-V-Logikfreigabe",signal:"PG_5V0",connection:"Versorgung → Power-Good → Pico W",pin:"GP7",configured:true,live:function(s){if(s.power_good===null)return unknown();return s.power_good?{state:"ERKANNT",tone:"detected",value:"Power Good aktiv"}:{state:"NICHT ERKANNT",tone:"neutral",value:"12-V-Pfad nicht freigegeben"};}},
 {id:"wifi",name:"WLAN Client",short:"WLAN",group:"connectivity",position:[27,60],anchor:[-1.68,-.07,.16],explode:[-.72,-.20,0],role:"Verbindet den Pico W als Client mit dem konfigurierten Präsentations-Hotspot",signal:"CYW43 / DHCP",connection:"Pico W ↔ WLAN-Hotspot",pin:"2,4 GHz",configured:true,live:function(s){if(s.wifi===null)return unknown();return s.wifi?{state:"ERKANNT",tone:"detected",value:s.wifi_ssid+" · "+s.wifi_ip}:{state:"NICHT ERKANNT",tone:"neutral",value:"WLAN getrennt"};}},
 {id:"webserver",name:"HTTP-Webserver",short:"Webserver",group:"connectivity",position:[28,64],anchor:[-1.42,-.07,.16],explode:[-.72,-.20,0],role:"Liefert Dashboard und API aus dem Pico-Flash",signal:"HTTP / TCP",connection:"Port 80 über aktuelle DHCP-IP",pin:"lwIP Raw API",configured:true,live:detected("webserver_ready",function(){return"HTTP bereit";})}
];
})();
