(function(){
"use strict";
var components=window.V4_COMPONENTS||[],preview=false,current=null,online=false,activeId="",connected=new Set();
var groups={physical:"GERÄT",thermal:"WÄRMEWEG",sensors:"SENSORIK",power:"LEISTUNG",control:"STEUERUNG",interface:"BEDIENUNG",auxiliary:"UMGEBUNG",connectivity:"VERBINDUNG"};
var configurable=["temp1","temp2","peltier1","peltier2","fan","light","oled","buttons","rgb","cup","adc","current1","current2","leds","power"];
var positions={temp1:[42,70],temp2:[66,43],peltier1:[27,52],peltier2:[77,52],fan:[84,70],light:[82,54],oled:[72,74],buttons:[74,85],rgb:[51,52],cup:[51,73],adc:[29,73],current1:[27,82],current2:[32,84],leds:[30,88],power:[11,78]};
function byId(id){return document.getElementById(id);}function all(selector){return Array.prototype.slice.call(document.querySelectorAll(selector));}function component(id){return components.find(function(item){return item.id===id;});}function create(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function liveFor(item){if(preview&&!connected.has(item.id))return{state:"NICHT ANGESCHLOSSEN",tone:"neutral",value:"—"};if(!current||!online)return{state:"NICHT VERFÜGBAR",tone:"unknown",value:"—"};return item.live(current,online);}
function connectedState(item,live){if(preview)return connected.has(item.id)?"JA":"NEIN";if(!online)return"NICHT VERFÜGBAR";if(live.tone==="valid"||live.tone==="detected"||live.tone==="active"||live.tone==="fault")return"JA";if(live.tone==="neutral")return"NICHT ANGESCHLOSSEN";return"NICHT DIREKT ÜBERWACHT";}
function simpleLive(live){if(live.tone==="fault")return"FEHLER";if(live.state.indexOf("NICHT DIREKT")===0)return"NICHT DIREKT ÜBERWACHT";if(live.state.indexOf("NICHT")===0)return live.state;if(live.tone==="active")return"AKTIV";if(live.tone==="valid"||live.tone==="detected")return"VERFÜGBAR";return"NICHT DIREKT ÜBERWACHT";}
function setVisualState(id,enabled,animate){all('[data-part="'+id+'"]').forEach(function(part){part.classList.toggle("disconnected",!enabled);if(enabled&&animate){part.classList.remove("assembling");void part.getBoundingClientRect();part.classList.add("assembling");setTimeout(function(){part.classList.remove("assembling");},500);}});var control=document.querySelector('[data-component-control="'+id+'"]');if(control){control.classList.toggle("connected",enabled);control.innerHTML=(enabled?"✓":"+")+"<span>"+component(id).short+"</span>";control.setAttribute("aria-label",component(id).name+(preview?(enabled?" entfernen":" hinzufügen"):" anzeigen"));}var item=document.querySelector('[data-configure="'+id+'"]');if(item){item.classList.toggle("connected",enabled);item.querySelector("b").textContent=enabled?"✓":"+";item.setAttribute("aria-label",component(id).name+(preview?(enabled?" entfernen":" hinzufügen"):" anzeigen"));}}
function buildDirectControls(){var host=byId("componentHotspots");configurable.forEach(function(id){var item=component(id),position=positions[id];if(!item||!position)return;var button=create("button","component-control");button.type="button";button.dataset.componentControl=id;button.style.left=position[0]+"%";button.style.top=position[1]+"%";button.addEventListener("click",function(){preview?toggleConnection(id):focus(id);});host.appendChild(button);setVisualState(id,true,false);});}
function buildConfiguration(){var host=byId("configurationList");components.forEach(function(item){connected.add(item.id);});configurable.forEach(function(id){var item=component(id),button=create("button","component-item");button.type="button";button.dataset.configure=id;button.innerHTML="<span>"+item.short+"</span><b>✓</b>";button.addEventListener("click",function(){preview?toggleConnection(id):focus(id);});host.appendChild(button);});byId("configurationHint").textContent=preview?"Plus oder Haken verändert nur die lokale Illustration.":"Live-System: Bauteile auswählen, Konfiguration bleibt schreibgeschützt.";syncAll(false);}
function syncAll(animateId){configurable.forEach(function(id){setVisualState(id,connected.has(id),animateId===id);});}
function toggleConnection(id){var enabled=!connected.has(id);if(enabled)connected.add(id);else connected.delete(id);setVisualState(id,enabled,enabled);focus(id);}
function setConnected(ids){if(!preview)return;connected.clear();(ids||[]).forEach(function(id){connected.add(id);});["pico","wifi","webserver"].forEach(function(id){connected.add(id);});syncAll(false);if(activeId)renderLens(component(activeId));}
function focus(id){var item=component(id);if(!item)return;activeId=id;all("[data-focus]").forEach(function(node){node.classList.toggle("focused",node.dataset.focus===id);});all(".component-control").forEach(function(node){node.classList.toggle("active",node.dataset.componentControl===id);});all(".component-item").forEach(function(node){node.classList.toggle("active",node.dataset.configure===id);});renderLens(item);}
function renderLens(item){var live=liveFor(item);byId("componentGroup").textContent=groups[item.group]||"BAUTEIL";byId("componentName").textContent=item.name;byId("componentRole").textContent=item.role;byId("componentPlanned").textContent="JA";byId("componentConnected").textContent=connectedState(item,live);byId("componentLive").textContent=simpleLive(live);byId("componentMeasurement").textContent=live.value||"—";}
function update(status,isOnline){current=status;online=!!isOnline;components.forEach(function(item){var live=liveFor(item);all('[data-part="'+item.id+'"]').forEach(function(part){part.classList.toggle("component-fault",live.tone==="fault");});if(!preview&&configurable.indexOf(item.id)>=0){var enabled=connectedState(item,live)!=="NICHT ANGESCHLOSSEN";if(enabled)connected.add(item.id);else connected.delete(item.id);setVisualState(item.id,enabled,false);}});if(activeId)renderLens(component(activeId));}
function bindParts(){all("[data-focus]").forEach(function(node){function select(){focus(node.dataset.focus);}node.addEventListener("click",select);node.addEventListener("keydown",function(event){if(event.key==="Enter"||event.key===" "){event.preventDefault();select();}});});}
function initialise(options){preview=!!(options&&options.preview);buildDirectControls();buildConfiguration();bindParts();focus("cup");var selected=new URLSearchParams(location.search).get("component");if(selected&&component(selected))focus(selected);}
window.V4Twin={initialise:initialise,update:update,focus:focus,setConnected:setConnected,connected:connected};
})();
