(function(){
"use strict";
var components=window.V4_COMPONENTS||[],preview=false,current=null,online=false,activeId="",configured=new Set(),connected=new Set(),guideIndex=0,guideTimer=0,storyObserver=null;
var groups={physical:"PHYSICAL SYSTEM",thermal:"THERMAL SYSTEM",sensors:"SENSORS",power:"POWER",control:"CONTROL CORE",interface:"HUMAN INTERFACE",auxiliary:"AUXILIARY SYSTEM",connectivity:"CONNECTIVITY"};
var configurationGroups=[
 {label:"TEMPERATUR",ids:["temp1","temp2"]},
 {label:"AKTORIK",ids:["peltier1","peltier2","fan","plate"]},
 {label:"SENSORIK",ids:["light","current1","current2","cup","adc"]},
 {label:"INTERFACE",ids:["oled","rgb","leds","buttons"]},
 {label:"SYSTEM",ids:["pico","power","wifi","webserver"]}
];
var guide=[
 {component:"temp1",title:"Messung",copy:"Der TMP36 erfasst den Istwert y(t) direkt an der thermischen Strecke."},
 {component:"cup",title:"Vergleich",copy:"Sollwert w(t) und Istwert y(t) bilden die Regelabweichung e(t)."},
 {component:"pico",title:"PI-Regler",copy:"Der Pico W berechnet aus P- und I-Anteil die Stellgröße u(t)."},
 {component:"peltier1",title:"Aktor",copy:"Die Heizkanäle wandeln u(t) ausschließlich in kontrollierten Wärmeeintrag um."},
 {component:"plate",title:"Regelstrecke",copy:"Heizplatte, Becher und Inhalt bilden die träge thermische Strecke G(s)."},
 {component:"temp1",title:"Rückführung",copy:"Der Sensor misst den neuen Istwert. y(t) wird zum Vergleichspunkt zurückgeführt."}
];
function byId(id){return document.getElementById(id);}
function all(selector){return Array.prototype.slice.call(document.querySelectorAll(selector));}
function component(id){return components.find(function(item){return item.id===id;});}
function create(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function liveFor(item){if(!configured.has(item.id))return{state:"NICHT KONFIGURIERT",tone:"neutral",value:"Nicht Bestandteil des Systems"};if(preview&&!connected.has(item.id))return{state:"NICHT ANGESCHLOSSEN",tone:"neutral",value:"In dieser Vorschau nicht angeschlossen"};if(!current)return{state:"NICHT VERFÜGBAR",tone:"unknown",value:"Noch keine Statusdaten"};return item.live(current,online);}
function wirePath(item){var pico=component("pico"),x1=item.position[0],y1=item.position[1],x2=pico.position[0],y2=pico.position[1],cx=(x1+x2)/2;return"M"+x1+" "+y1+"C"+cx+" "+y1+" "+cx+" "+y2+" "+x2+" "+y2;}
function buildWires(){var ns="http"+"://www.w3.org/2000/svg",svg=document.createElementNS(ns,"svg");svg.setAttribute("class","twin-signal-web");svg.setAttribute("viewBox","0 0 100 100");svg.setAttribute("preserveAspectRatio","none");svg.setAttribute("aria-hidden","true");components.filter(function(item){return item.id!=="pico"&&item.group!=="physical";}).forEach(function(item){var path=document.createElementNS(ns,"path");path.setAttribute("d",wirePath(item));path.dataset.component=item.id;path.dataset.group=item.group;svg.appendChild(path);});byId("visualStage").insertBefore(svg,byId("twinHotspots"));}
function buildHotspots(){var host=byId("twinHotspots");components.forEach(function(item){var button=create("button","twin-hotspot");button.type="button";button.dataset.component=item.id;button.style.left=item.position[0]+"%";button.style.top=item.position[1]+"%";button.setAttribute("aria-label",item.name+" öffnen");button.innerHTML="<i>+</i><span>"+item.short+"</span>";button.addEventListener("click",function(){focus(item.id);});host.appendChild(button);});}
function configurationButton(item){var button=create("button","configuration-item");button.type="button";button.dataset.configure=item.id;button.innerHTML="<i></i><span><strong>"+item.short+"</strong><small>"+groups[item.group]+"</small></span><b>VORGESEHEN</b>";button.setAttribute("aria-pressed","true");button.addEventListener("click",function(){if(!preview){focus(item.id);closeConfiguration();return;}toggleConnection(item.id);});return button;}
function buildConfiguration(){var host=byId("configurationList");components.forEach(function(item){configured.add(item.id);connected.add(item.id);});configurationGroups.forEach(function(group){var section=create("section","configuration-group"),title=create("h3","",group.label);section.appendChild(title);group.ids.forEach(function(id){var item=component(id);if(item)section.appendChild(configurationButton(item));});host.appendChild(section);});byId("configurationHint").textContent=preview?"Lokale Vorschau · Änderungen betreffen niemals Hardware; Anschlussprofile sind reine Simulation.":"Live-System · Vorgesehene Konfiguration ist schreibgeschützt.";updateCount();}
function updateCount(){byId("configuredCount").textContent=preview?configured.size+" vorgesehen · "+connected.size+" angeschlossen":configured.size+" Komponenten vorgesehen";}
function paintConnection(id,enabled,animate){var button=document.querySelector('[data-configure="'+id+'"]'),spot=document.querySelector('.twin-hotspot[data-component="'+id+'"]'),wire=document.querySelector('.twin-signal-web [data-component="'+id+'"]');if(button){button.setAttribute("aria-pressed",String(enabled));button.classList.toggle("removed",!enabled);button.querySelector("b").textContent=enabled?"ANGESCHLOSSEN":"NICHT ANGESCHLOSSEN";}if(spot){spot.classList.toggle("not-configured",!enabled);if(enabled&&animate){spot.classList.add("assembling");setTimeout(function(){spot.classList.remove("assembling");},800);}}if(wire)wire.classList.toggle("not-configured",!enabled);}
function toggleConnection(id){var enabled=!connected.has(id);if(enabled)connected.add(id);else connected.delete(id);paintConnection(id,enabled,enabled);updateCount();if(activeId===id)renderLens(component(id));}
function setConnected(ids){if(!preview)return;connected.clear();(ids||[]).forEach(function(id){if(configured.has(id))connected.add(id);});components.forEach(function(item){paintConnection(item.id,connected.has(item.id),false);});updateCount();if(activeId)renderLens(component(activeId));}
function focus(id){var item=component(id);if(!item)return;activeId=id;document.body.dataset.component=id;document.body.classList.add("component-focused");all(".twin-hotspot").forEach(function(node){node.classList.toggle("active",node.dataset.component===id);});all(".twin-signal-web path").forEach(function(path){path.classList.toggle("active",path.dataset.component===id);});var stage=byId("visualStage"),dx=(50-item.position[0])*.12,dy=(52-item.position[1])*.08;stage.style.setProperty("--focus-x",dx+"vw");stage.style.setProperty("--focus-y",dy+"vh");if(window.ProductScene)window.ProductScene.setFocus(item.group==="sensors"?"sensors":item.group==="power"||item.id.indexOf("peltier")===0?"power":"system");renderLens(item);byId("componentLens").classList.add("open");byId("componentLens").setAttribute("aria-hidden","false");}
function clearFocus(){activeId="";delete document.body.dataset.component;document.body.classList.remove("component-focused");all(".twin-hotspot,.twin-signal-web path").forEach(function(node){node.classList.remove("active");});byId("componentLens").classList.remove("open");byId("componentLens").setAttribute("aria-hidden","true");if(window.ProductScene)window.ProductScene.setFocus("system");}
function renderLens(item){if(!item)return;var live=liveFor(item),isConfigured=configured.has(item.id);byId("componentGroup").textContent=groups[item.group]||"SYSTEM";byId("componentName").textContent=item.name;byId("componentRole").textContent=item.role;byId("componentSignal").textContent=item.signal;byId("componentConnection").textContent=item.connection;byId("componentPin").textContent=item.pin;byId("componentConfigured").textContent=isConfigured?"VORGESEHEN":"NICHT KONFIGURIERT";var liveNode=byId("componentLive");liveNode.textContent=live.state;liveNode.dataset.tone=live.tone;byId("componentValue").textContent=live.value||"—";}
function openConfiguration(){byId("configurationDrawer").classList.add("open");byId("configurationDrawer").setAttribute("aria-hidden","false");}
function closeConfiguration(){byId("configurationDrawer").classList.remove("open");byId("configurationDrawer").setAttribute("aria-hidden","true");}
function setLens(lens){document.body.dataset.lens=lens;all("[data-lens]").forEach(function(button){button.classList.toggle("active",button.dataset.lens===lens);});if(window.ProductScene)window.ProductScene.setLens(lens);if(window.ThermalOverlay)window.ThermalOverlay.setMode(lens==="thermal"?"thermal":"overview");}
function startGuide(){closeConfiguration();guideIndex=0;byId("guidedJourney").classList.add("open");byId("guidedJourney").setAttribute("aria-hidden","false");document.body.classList.add("guide-active");if(window.V3UI&&window.V3UI.setMode)window.V3UI.setMode("control");showGuide();}
function closeGuide(){clearTimeout(guideTimer);document.body.classList.remove("guide-active");byId("guidedJourney").classList.remove("open");byId("guidedJourney").setAttribute("aria-hidden","true");clearFocus();}
function showGuide(){clearTimeout(guideTimer);var step=guide[guideIndex];byId("guideCounter").textContent=String(guideIndex+1).padStart(2,"0")+" / 06";byId("guideTitle").textContent=step.title;byId("guideCopy").textContent=step.copy;byId("guideProgress").style.setProperty("--guide-progress",((guideIndex+1)/guide.length*100)+"%");focus(step.component);document.body.dataset.guide=String(guideIndex+1);guideTimer=setTimeout(function(){guideIndex=(guideIndex+1)%guide.length;showGuide();},5200);}
function moveGuide(delta){guideIndex=(guideIndex+delta+guide.length)%guide.length;showGuide();}
function storyMode(name){return name==="configure"?"product":name==="engineering"?"engineering":"control";}
function applyStory(name){document.body.dataset.story=name;var mode=storyMode(name);if(window.V3UI&&window.V3UI.setMode)window.V3UI.setMode(mode);if(name==="engineering")setLens("signals");else if(name==="configure")setLens("product");if(name!=="configure")clearFocus();}
function buildStory(){var chapters=all("[data-story-step]");if("IntersectionObserver" in window){storyObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting&&entry.intersectionRatio>.42)applyStory(entry.target.dataset.storyStep);});},{threshold:[.42,.62],rootMargin:"-8% 0px -8% 0px"});chapters.forEach(function(section){storyObserver.observe(section);});}all("[data-mode]").forEach(function(button){button.addEventListener("click",function(){var target={product:"configure",control:"loop",engineering:"engineering"}[button.dataset.mode];if(target){var chapter=document.querySelector('[data-story-step="'+target+'"]');if(chapter)chapter.scrollIntoView({behavior:document.body.classList.contains("low-motion")?"auto":"smooth"});}});});}
function updateSignalAvailability(status){var available={temperature:status.temp1_ok===true,target:status.setpoint_supplied===true,temperature2:status.temp2_ok===true,power:status.power_supplied===true,current1:status.current1_ok===true,current2:status.current2_ok===true,fan:status.fan_supplied===true,light:status.light_ok===true};Object.keys(available).forEach(function(key){var button=document.querySelector('[data-signal="'+key+'"]');if(button){button.hidden=!available[key];button.disabled=!available[key];}});}
function buildSafety(status){var host=byId("safetyMatrix");if(!host)return;function safety(label,value,relevant){var state=value===true?"BEREIT":value===false?(relevant?"NICHT FREIGEGEBEN":"NICHT ERKANNT"):"NICHT VERFÜGBAR";return{label:label,state:state,tone:value===true?"valid":value===false&&relevant?"fault":"neutral",relevant:relevant};}var rows=[safety("Temperatur",status.sensor_ok,true),safety("Strommessung",status.current_ok,true),safety("Lüfter",status.fault==="LUEFTER"?false:status.fan_supplied===true?true:null,true),safety("Becher",status.cup,true),safety("Versorgung",status.power_good,true),safety("Sensorbus",status.tla2024_ok,false),safety("WLAN",status.wifi,false),safety("Webserver",status.webserver_ready,false)];host.replaceChildren();rows.forEach(function(row){var item=create("span","safety-check");item.dataset.tone=row.tone;item.innerHTML="<i></i><small>"+(row.relevant?"SAFETY":"SYSTEM")+"</small><strong>"+row.label+"</strong><b>"+row.state+"</b>";host.appendChild(item);});}
function update(status,isOnline){current=status;online=!!isOnline;components.forEach(function(item){var spot=document.querySelector('.twin-hotspot[data-component="'+item.id+'"]');if(!spot)return;var live=liveFor(item);spot.dataset.tone=live.tone;spot.title=item.name+" · "+live.state;});all("[data-configure]").forEach(function(button){var item=component(button.dataset.configure),live=liveFor(item);button.dataset.tone=live.tone;button.querySelector("b").textContent=preview&&!connected.has(item.id)?"NICHT ANGESCHLOSSEN":live.state;});updateSignalAvailability(status);buildSafety(status);if(activeId)renderLens(component(activeId));}
function setMode(mode){if(mode==="thermal")setLens("thermal");else if(mode==="engineering")setLens("signals");else if(mode==="product"&&document.body.dataset.story==="configure")setLens("product");}
function initialise(options){preview=!!(options&&options.preview);buildWires();buildHotspots();buildConfiguration();buildStory();all("[data-lens]").forEach(function(button){button.addEventListener("click",function(){setLens(button.dataset.lens);});});byId("componentClose").addEventListener("click",clearFocus);byId("configureButton").addEventListener("click",openConfiguration);byId("configurationClose").addEventListener("click",closeConfiguration);byId("journeyButton").addEventListener("click",startGuide);byId("guideClose").addEventListener("click",closeGuide);byId("guidePrevious").addEventListener("click",function(){moveGuide(-1);});byId("guideNext").addEventListener("click",function(){moveGuide(1);});byId("visualStage").addEventListener("click",function(event){if(event.target.closest("button,.component-lens,.configuration-drawer,.guided-journey"))return;if(activeId)clearFocus();});addEventListener("keydown",function(event){if(event.key==="Escape"){closeGuide();closeConfiguration();clearFocus();}});var query=new URLSearchParams(location.search);setTimeout(function(){var story=query.get("story"),lens=query.get("lens"),selected=query.get("component");if(story){var chapter=document.querySelector('[data-story-step="'+story+'"]');if(chapter){chapter.scrollIntoView({behavior:"auto"});applyStory(story);}}if(lens)setLens(lens);if(selected)focus(selected);if(query.has("configure"))openConfiguration();if(query.has("guide"))startGuide();},80);}
window.V4Twin={initialise:initialise,update:update,setMode:setMode,setLens:setLens,focus:focus,clearFocus:clearFocus,setConnected:setConnected,configured:configured,connected:connected};
})();
