(function(){
"use strict";
var PREVIEW=__PREVIEW_MODE__,SAMPLE_INTERVAL=500,MAX_HISTORY_SECONDS=1800;
var history=[],runtime={online:false,initial:true,busy:false,current:null,lastUpdate:0,range:60,drawQueued:false,mode:"overview",focus:"system",lowMotion:matchMedia("(prefers-reduced-motion: reduce)").matches};
var narratives={AUS:"Leistungspfad sicher deaktiviert",BEREIT:"System bereit für einen bewussten Start",AUFHEIZEN:"PI-Regler führt thermische Energie zu",HALTEN:"Solltemperatur erreicht · Energie wird nachgeführt",FEHLER:"Safety Lock aktiv · Heizleistung gesperrt"};
var faultCopy={"KEIN FEHLER":"Keine aktive Störung",TEMPERATURSENSOR:"Temperatursignal fehlt oder ist unplausibel",UEBERTEMPERATUR:"Maximale sichere Temperatur überschritten",LUEFTER:"Kein plausibles Tachosignal bei Heizleistung",UEBERSTROM:"Stromgrenze eines Heizkanals überschritten",STROMSENSOR:"Strommessung ist nicht plausibel",BECHER_ENTFERNT:"Becher wurde während des Heizvorgangs entfernt",VERSORGUNG:"12-V-Leistungsversorgung nicht freigegeben"};
var byId=function(id){return document.getElementById(id);},all=function(selector){return Array.prototype.slice.call(document.querySelectorAll(selector));};
function number(value,fallback){var parsed=typeof value==="string"?Number(value.replace(",",".")):Number(value);return Number.isFinite(parsed)?parsed:(fallback===undefined?0:fallback);}
function truth(value,fallback){return typeof value==="boolean"?value:!!fallback;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function fixed(value,digits){digits=digits===undefined?1:digits;return Number.isFinite(Number(value))?Number(value).toFixed(digits).replace(".",","):"—";}
function text(id,value){var node=byId(id);if(node)node.textContent=value;}
function normalize(source){source=source||{};var temperature=number(source.temperature,NaN),setpoint=number(source.setpoint,45),states=["AUS","BEREIT","AUFHEIZEN","HALTEN","FEHLER"],fault=String(source.fault||"KEIN FEHLER");return{
 state:states.indexOf(source.state)>=0?source.state:"AUS",fault:fault,fault_description:String(source.fault_description||faultCopy[fault]||"Unbekannter Systemfehler"),temperature:temperature,temperature1:number(source.temperature1,NaN),temperature2:number(source.temperature2,NaN),setpoint:setpoint,error:Number.isFinite(Number(source.error))?Number(source.error):setpoint-temperature,power:clamp(number(source.power),0,100),fan_rpm:Math.max(0,number(source.fan_rpm)),fan_percent:clamp(number(source.fan_percent),0,100),current1:Math.max(0,number(source.current1)),current2:Math.max(0,number(source.current2)),light_level:clamp(number(source.light_level),0,1),sensor_ok:truth(source.sensor_ok),temp1_ok:truth(source.temp1_ok),temp2_ok:truth(source.temp2_ok),current_ok:truth(source.current_ok),current1_ok:truth(source.current1_ok),current2_ok:truth(source.current2_ok),tla2024_ok:truth(source.tla2024_ok),light_ok:truth(source.light_ok),display_initialized:truth(source.display_initialized),leds_initialized:truth(source.leds_initialized),cup:truth(source.cup),power_good:truth(source.power_good),wifi:truth(source.wifi),webserver_ready:truth(source.webserver_ready),wifi_ssid:String(source.wifi_ssid||"—"),wifi_ip:String(source.wifi_ip||"—"),night:truth(source.night),start_allowed:truth(source.start_allowed),start_block_reason:String(source.start_block_reason||"Startfreigabe nicht bestätigt"),kp:number(source.kp),ki:number(source.ki),p_term:number(source.p_term),i_term:number(source.i_term),output_limited:truth(source.output_limited),anti_windup:truth(source.anti_windup),control_period_ms:Math.max(0,number(source.control_period_ms)),max_safe_temperature:number(source.max_safe_temperature,65),uptime_ms:Math.max(0,number(source.uptime_ms))};}
function setOnline(online,message){runtime.online=!!online;document.body.dataset.live=String(runtime.online);text("connectionState",online?"LIVE · PICO W":"SIGNAL UNTERBROCHEN");if(!online){text("networkName",message||"Pico nicht erreichbar");text("lastSignal",runtime.lastUpdate?new Date(runtime.lastUpdate).toLocaleTimeString("de-DE"):"—");}else{text("lastSignal","LIVE "+new Date(runtime.lastUpdate||Date.now()).toLocaleTimeString("de-DE"));}}
function addHistory(status,time){var stamp=time||Date.now(),previous=history[history.length-1];if(previous&&stamp-previous.time<450)return;history.push({time:stamp,temperature:status.temperature,temperature2:status.temperature2,target:status.setpoint,power:status.power,valid:status.sensor_ok&&Number.isFinite(status.temperature),valid2:status.temp2_ok&&Number.isFinite(status.temperature2)});var earliest=stamp-MAX_HISTORY_SECONDS*1000;while(history.length&&history[0].time<earliest)history.shift();scheduleChart();}
function scheduleChart(){if(runtime.drawQueued)return;runtime.drawQueued=true;requestAnimationFrame(function(){runtime.drawQueued=false;drawChart();});}
function drawChart(){var canvas=byId("timelineCanvas");if(!canvas)return;var rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}var ctx=canvas.getContext("2d");ctx.setTransform(ratio,0,0,ratio,0,0);var w=rect.width,h=rect.height,left=37,right=39,top=14,bottom=22;ctx.clearRect(0,0,w,h);var now=history.length?history[history.length-1].time:Date.now(),from=now-runtime.range*1000,data=history.filter(function(point){return point.time>=from;});var temps=[];data.forEach(function(point){if(point.valid)temps.push(point.temperature);if(point.valid2)temps.push(point.temperature2);temps.push(point.target);});var min=temps.length?Math.floor(Math.min.apply(null,temps)-2):20,max=temps.length?Math.ceil(Math.max.apply(null,temps)+2):60,span=Math.max(7,max-min);function x(time){return left+(time-from)/(runtime.range*1000)*(w-left-right);}function y(value){return top+(max-value)/span*(h-top-bottom);}ctx.font="7px ui-monospace,monospace";ctx.fillStyle="#55717b";ctx.strokeStyle="rgba(77,126,141,.16)";ctx.lineWidth=1;for(var i=0;i<4;i++){var yy=top+i/3*(h-top-bottom),label=(max-i/3*span).toFixed(0)+"°";ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillText(label,1,yy+3);}for(var j=0;j<6;j++){var xx=left+j/5*(w-left-right);ctx.beginPath();ctx.moveTo(xx,top);ctx.lineTo(xx,h-bottom);ctx.stroke();if(j<5)ctx.fillText("−"+Math.round(runtime.range*(5-j)/5)+"s",xx-8,h-5);}
 function line(key,color,lineWidth,predicate){ctx.beginPath();var started=false;data.forEach(function(point){if(!predicate(point)||!Number.isFinite(point[key])){started=false;return;}var px=x(point.time),py=y(point[key]);if(started)ctx.lineTo(px,py);else ctx.moveTo(px,py);started=true;});ctx.strokeStyle=color;ctx.lineWidth=lineWidth;ctx.lineJoin="round";ctx.lineCap="round";ctx.stroke();}
 if(data.length){var fill=ctx.createLinearGradient(0,top,0,h-bottom);fill.addColorStop(0,"rgba(255,135,66,.20)");fill.addColorStop(1,"rgba(255,135,66,0)");ctx.beginPath();var begun=false;data.forEach(function(point){if(!point.valid)return;var px=x(point.time),py=y(point.temperature);if(!begun){ctx.moveTo(px,h-bottom);ctx.lineTo(px,py);}else ctx.lineTo(px,py);begun=true;});if(begun){ctx.lineTo(x(data[data.length-1].time),h-bottom);ctx.closePath();ctx.fillStyle=fill;ctx.fill();}}
 line("target","rgba(104,226,241,.82)",1,function(){return true;});line("temperature2","rgba(157,172,205,.52)",1,function(point){return point.valid2;});line("temperature","#ff9a54",2.4,function(point){return point.valid;});ctx.beginPath();var started=false;data.forEach(function(point){var px=x(point.time),py=top+(100-point.power)/100*(h-top-bottom);if(started)ctx.lineTo(px,py);else ctx.moveTo(px,py);started=true;});ctx.strokeStyle="rgba(110,224,168,.66)";ctx.lineWidth=1.25;ctx.stroke();if(data.length){var latest=data[data.length-1],cursor=x(latest.time);ctx.strokeStyle="rgba(225,247,250,.23)";ctx.beginPath();ctx.moveTo(cursor,top);ctx.lineTo(cursor,h-bottom);ctx.stroke();if(latest.valid){ctx.fillStyle="#ffd1ae";ctx.beginPath();ctx.arc(cursor,y(latest.temperature),3.5,0,Math.PI*2);ctx.fill();}}}
function engineeringValues(status){var host=byId("engineeringValues");if(!host)return;var values=[["12 V",status.power_good?"FREIGEGEBEN":"GESPERRT"],["3,3 V","LOGIK OK"],["P1",fixed(status.current1,2)+" A"],["P2",fixed(status.current2,2)+" A"],["LICHT",Math.round(status.light_level*100)+" %"],["UPTIME",Math.floor(status.uptime_ms/60000)+" min"]];host.replaceChildren();values.forEach(function(pair){var node=document.createElement("span"),small=document.createElement("small"),strong=document.createElement("strong");small.textContent=pair[0];strong.textContent=pair[1];node.append(small,strong);host.appendChild(node);});}
function render(statusInput,options){var status=normalize(statusInput),record=!options||options.record!==false;runtime.current=status;document.body.dataset.state=status.state;document.body.classList.remove("is-loading");var active=status.state==="AUFHEIZEN"||status.state==="HALTEN",temperatureAvailable=status.sensor_ok&&Number.isFinite(status.temperature),controls=runtime.online;
 text("networkName",status.wifi?status.wifi_ssid:"WLAN getrennt");text("networkIp",status.wifi_ip!=="—"?status.wifi_ip:"—");text("lastSignal",runtime.lastUpdate?"LIVE "+new Date(runtime.lastUpdate).toLocaleTimeString("de-DE"):"—");text("actualTemperature",temperatureAvailable?fixed(status.temperature):"—");byId("actualTemperature").classList.toggle("unavailable",!temperatureAvailable);text("sensorQuality",temperatureAvailable?(status.night?"NACHTMODUS":"TAGMODUS")+" · SENSOR PLAUSIBEL":"MESSWERT NICHT VERFÜGBAR");text("systemState",status.state);text("stateNarrative",narratives[status.state]);text("loopSetpoint",fixed(status.setpoint)+" °C");text("loopDeviation",Number.isFinite(status.error)?(status.error>=0?"+":"")+fixed(status.error)+" K":"—");text("piNodeState",active?"REGELT":"INAKTIV");text("loopOutput",fixed(status.power,0)+" %");text("loopSensor",temperatureAvailable?fixed(status.temperature)+" °C":"—");text("plantState",active?(status.state==="HALTEN"?"STABIL":"ERWÄRMT"):"STILLSTAND");
 var orbit=byId("targetOrbit"),level=clamp((status.setpoint-20)/40*100,0,100),angle=level*.75*3.6;orbit.style.setProperty("--target-level",level.toFixed(1));orbit.style.setProperty("--target-angle",angle.toFixed(1)+"deg");if(document.activeElement!==byId("targetInput"))byId("targetInput").value=fixed(status.setpoint);text("powerOutput",fixed(status.power,0)+" %");byId("outputFill").style.width=status.power+"%";text("peltierDetail",active?"P1 "+fixed(status.current1,2)+" A · P2 "+fixed(status.current2,2)+" A":"P1 / P2 sicher aus");text("fanRpm",fixed(status.fan_rpm,0)+" rpm");document.documentElement.style.setProperty("--fan-period",status.fan_percent>0?Math.max(.4,3.5-status.fan_percent*.03)+"s":"0s");
 text("piKp",fixed(status.kp,3));text("piKi",fixed(status.ki,3));text("piP",fixed(status.p_term)+" %");text("piI",fixed(status.i_term)+" %");text("piWindup",status.anti_windup?"AKTIV":status.output_limited?"BEGRENZT":"BEREIT");text("piCycle",fixed(status.control_period_ms,0)+" ms");
 text("startActionLabel",active?"AKTIV":"START");text("startActionHint",active?"REGELKREIS":"HEIZVORGANG");var blocked=!status.start_allowed&&!active,fault=status.state==="FEHLER"||status.fault!=="KEIN FEHLER";byId("safetyLock").classList.toggle("visible",blocked||fault);text("safetyTitle",fault?status.fault:"System nicht bereit");text("safetyReason",fault?status.fault_description:status.start_block_reason);text("actionReason",!controls?"Keine Live-Verbindung":active?"Regelkreis aktiv":status.start_allowed?"Alle Freigaben bestätigt":status.start_block_reason);byId("startButton").disabled=!controls||!status.start_allowed||active;byId("stopButton").disabled=!controls;byId("setpointButton").disabled=!controls;byId("targetDown").disabled=!controls;byId("targetUp").disabled=!controls;byId("targetInput").disabled=!controls;
 text("engCup",temperatureAvailable?fixed(status.temperature)+" °C · w(t) "+fixed(status.setpoint)+" °C":"Messung offen");text("engSensors","T1 "+(status.temp1_ok?fixed(status.temperature1)+" °C":"FEHLER")+" · T2 "+(status.temp2_ok?fixed(status.temperature2)+" °C":"FEHLER"));text("engPlate",active?fixed(status.power,0)+" % Wärmeeintrag":"sicher aus");text("engPeltier","P1 "+fixed(status.current1,2)+" A · P2 "+fixed(status.current2,2)+" A");text("engFan",fixed(status.fan_rpm,0)+" rpm · "+fixed(status.fan_percent,0)+" %");text("engPico",status.wifi?status.wifi_ip:"WLAN getrennt");text("engAdc",status.tla2024_ok?"online · Licht "+Math.round(status.light_level*100)+" %":"nicht verfügbar");engineeringValues(status);text("offlineLastValue",temperatureAvailable?"Letzte Temperatur: "+fixed(status.temperature)+" °C":"Letzte Systemaufnahme bleibt sichtbar");
 if(record)addHistory(status);if(window.ProductScene)window.ProductScene.update(status);if(window.ThermalOverlay)window.ThermalOverlay.update(status);if(!document.documentElement.dataset.uiReadyMs)document.documentElement.dataset.uiReadyMs=performance.now().toFixed(1);runtime.initial=false;}
async function fetchWithTimeout(url,options){var controller=new AbortController(),timeout=setTimeout(function(){controller.abort();},1800);try{return await fetch(url,Object.assign({cache:"no-store",signal:controller.signal},options||{}));}finally{clearTimeout(timeout);}}
async function poll(){if(PREVIEW||runtime.busy)return;runtime.busy=true;try{var response=await fetchWithTimeout("/api/status");if(!response.ok)throw new Error("HTTP "+response.status);var status=await response.json();runtime.lastUpdate=Date.now();setOnline(true);render(status);}catch(error){setOnline(false,runtime.initial?"Warte auf Pico W":"Live-API nicht erreichbar");}finally{runtime.busy=false;}}
async function command(path){if(!runtime.online)return;if(PREVIEW&&window.PreviewDriver){window.PreviewDriver.command(path);return;}var controls=["startButton","stopButton","setpointButton","targetDown","targetUp"].map(byId);controls.forEach(function(control){if(control)control.disabled=true;});try{var response=await fetchWithTimeout("/api/"+path,{method:"POST"}),result=await response.json().catch(function(){return{};});if(!response.ok)throw new Error(result.reason||"HTTP "+response.status);await poll();}catch(error){setOnline(false,"Befehl abgelehnt: "+error.message);}finally{if(runtime.current)render(runtime.current,{record:false});}}
function adjustTarget(delta){var input=byId("targetInput"),value=clamp(number(input.value,45)+delta,20,60),level=(value-20)/40*100;input.value=fixed(value);byId("targetOrbit").style.setProperty("--target-level",level);byId("targetOrbit").style.setProperty("--target-angle",(level*.75*3.6)+"deg");}
function setpoint(){var value=clamp(number(byId("targetInput").value,45),20,60);byId("targetInput").value=fixed(value);command("setpoint?value="+encodeURIComponent(value.toFixed(1)));}
function setMode(mode){runtime.mode=mode;document.body.dataset.mode=mode;all("[data-mode]").forEach(function(button){button.classList.toggle("active",button.dataset.mode===mode);});if(window.ProductScene)window.ProductScene.setMode(mode);if(window.ThermalOverlay)window.ThermalOverlay.setMode(mode);scheduleChart();}
function setFocus(focus){runtime.focus=focus;byId("engineeringLayer").dataset.focus=focus;all("[data-focus]").forEach(function(button){button.classList.toggle("active",button.dataset.focus===focus);});if(window.ProductScene)window.ProductScene.setFocus(focus);}
function togglePi(open){var panel=byId("piDetails"),show=open===undefined?!panel.classList.contains("open"):open;panel.classList.toggle("open",show);panel.setAttribute("aria-hidden",String(!show));byId("piNode").setAttribute("aria-expanded",String(show));if(show)byId("piClose").focus();}
function togglePresentation(){var active=!document.body.classList.contains("presentation");document.body.classList.toggle("presentation",active);byId("presentationButton").setAttribute("aria-pressed",String(active));if(active&&document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(function(){});if(!active&&document.fullscreenElement)document.exitFullscreen().catch(function(){});scheduleChart();if(window.ProductScene)window.ProductScene.resize();}
function interactions(){byId("startButton").addEventListener("click",function(){command("start");});byId("stopButton").addEventListener("click",function(){command("stop");});byId("setpointButton").addEventListener("click",setpoint);byId("targetDown").addEventListener("click",function(){adjustTarget(-.5);});byId("targetUp").addEventListener("click",function(){adjustTarget(.5);});byId("targetInput").addEventListener("change",function(){adjustTarget(0);});byId("targetInput").addEventListener("keydown",function(event){if(event.key==="Enter")setpoint();});all("[data-mode]").forEach(function(button){button.addEventListener("click",function(){setMode(button.dataset.mode);});});all("[data-focus]").forEach(function(button){button.addEventListener("click",function(){setFocus(button.dataset.focus);});});all("[data-range]").forEach(function(button){button.addEventListener("click",function(){runtime.range=number(button.dataset.range,60);all("[data-range]").forEach(function(item){item.classList.toggle("active",item===button);});scheduleChart();});});byId("piNode").addEventListener("click",function(){togglePi();});byId("piClose").addEventListener("click",function(){togglePi(false);});byId("presentationButton").addEventListener("click",togglePresentation);addEventListener("resize",scheduleChart,{passive:true});addEventListener("keydown",function(event){if(event.key==="Escape")togglePi(false);});document.addEventListener("fullscreenchange",function(){if(!document.fullscreenElement){document.body.classList.remove("presentation");byId("presentationButton").setAttribute("aria-pressed","false");}});}
function boot(){interactions();document.body.classList.toggle("low-motion",runtime.lowMotion);var frameRate=PREVIEW?60:30;if(window.ProductScene){window.ProductScene.initialise(byId("productCanvas"));window.ProductScene.setFrameRate(frameRate);window.ProductScene.setLowMotion(runtime.lowMotion);}if(window.ThermalOverlay){window.ThermalOverlay.initialise(byId("thermalCanvas"));window.ThermalOverlay.setFrameRate(frameRate);window.ThermalOverlay.setLowMotion(runtime.lowMotion);}var query=new URLSearchParams(location.search),skip=runtime.lowMotion||query.has("review")||query.has("scenario")||query.has("presentation")||query.has("engineering")||query.has("thermal");if(query.has("presentation"))document.body.classList.add("presentation");if(query.has("engineering"))setMode("engineering");else if(query.has("thermal"))setMode("thermal");if(skip)byId("intro").remove();else setTimeout(function(){var intro=byId("intro");if(intro)intro.remove();},1450);if(PREVIEW&&window.PreviewDriver){document.body.classList.add("preview-mode");window.PreviewDriver.start();}else{poll();setInterval(poll,SAMPLE_INTERVAL);}}
window.V3UI={acceptStatus:function(status,online){runtime.lastUpdate=Date.now();setOnline(online!==false,online===false?"Vorschau: Signal unterbrochen":"");render(status);},setOnline:setOnline,history:history,runtime:runtime,render:render,command:command,normalize:normalize,scheduleChart:scheduleChart};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
