(function(){
"use strict";
var PREVIEW=__PREVIEW_MODE__,POLL_MS=500,MAX_HISTORY_SECONDS=1800,CONTROLLER_HISTORY_SECONDS=300,history=[];
var runtime={online:false,everOnline:false,current:null,previous:null,lastUpdate:0,busy:false,drawQueued:false,range:60,signals:{temperature:true,target:true,power:true,temperature2:true,current1:false,current2:false,fan:false,light:false},token:"",tokenExpires:0,events:[],session:null,lastSession:null,recoveryTimer:0,targetDraft:false};
function byId(id){return document.getElementById(id);}
function all(selector){return Array.prototype.slice.call(document.querySelectorAll(selector));}
function text(id,value){var node=byId(id);if(node)node.textContent=value;}
function number(value,fallback){var n=Number(value);return Number.isFinite(n)?n:(fallback===undefined?NaN:fallback);}
function truth(value){return value===true||value===false?value:null;}
function fixed(value,digits){return Number.isFinite(Number(value))?Number(value).toFixed(digits===undefined?1:digits).replace(".",","):"—";}
function clamp(value,min,max){return Math.min(max,Math.max(min,value));}
function meter(id,value){var node=byId(id);if(node)node.style.width=clamp(number(value,0),0,100)+"%";}
function supplied(source,key){return Object.prototype.hasOwnProperty.call(source,key)&&source[key]!==null;}
function boolLabel(value,yes,no,unknown){return value===true?yes:value===false?no:(unknown||"NICHT VERFÜGBAR");}
function duration(milliseconds){if(!Number.isFinite(milliseconds)||milliseconds<0)return"—";var seconds=Math.floor(milliseconds/1000),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60),rest=seconds%60;return hours?hours+":"+String(minutes).padStart(2,"0")+":"+String(rest).padStart(2,"0"):minutes+":"+String(rest).padStart(2,"0")+" min";}
function responseTime(milliseconds){if(!Number.isFinite(milliseconds)||milliseconds<0)return"NOCH NICHT ERREICHT";var seconds=milliseconds/1000;return seconds<60?fixed(seconds,0)+" s":fixed(seconds/60,1)+" min";}
function normalize(source){
 source=source||{};
 return{state:String(source.state||"AUS"),fault:String(source.fault||"KEIN FEHLER"),fault_description:String(source.fault_description||"Keine Fehlerdetails"),temperature:number(source.temperature),temperature1:number(source.temperature1),temperature2:number(source.temperature2),setpoint:number(source.setpoint,45),error:number(source.error),power:number(source.power,0),fan_rpm:number(source.fan_rpm,0),fan_percent:number(source.fan_percent,0),current1:number(source.current1),current2:number(source.current2),light_level:number(source.light_level),supply_voltage:number(source.supply_voltage),setpoint_supplied:supplied(source,"setpoint"),power_supplied:supplied(source,"power"),fan_supplied:supplied(source,"fan_rpm"),sensor_ok:truth(source.sensor_ok),temp1_ok:truth(source.temp1_ok),temp2_ok:truth(source.temp2_ok),current_ok:truth(source.current_ok),current1_ok:truth(source.current1_ok),current2_ok:truth(source.current2_ok),tla2024_ok:truth(source.tla2024_ok),light_ok:truth(source.light_ok),display_initialized:truth(source.display_initialized),leds_initialized:truth(source.leds_initialized),cup:truth(source.cup),power_good:truth(source.power_good),wifi:truth(source.wifi),webserver_ready:truth(source.webserver_ready),wifi_ssid:String(source.wifi_ssid||"—"),wifi_ip:String(source.wifi_ip||"—"),night:truth(source.night),start_allowed:truth(source.start_allowed),start_block_reason:String(source.start_block_reason||"Startfreigabe nicht bestätigt"),kp:number(source.kp),ki:number(source.ki),p_term:number(source.p_term),i_term:number(source.i_term),output_limited:truth(source.output_limited),anti_windup:truth(source.anti_windup),control_period_ms:number(source.control_period_ms),max_safe_temperature:number(source.max_safe_temperature,65),uptime_ms:number(source.uptime_ms,0)};
}
function deltaTemperature(status){return status.temp1_ok===true&&status.temp2_ok===true&&Number.isFinite(status.temperature1)&&Number.isFinite(status.temperature2)?status.temperature1-status.temperature2:NaN;}
function totalCurrent(status){return status.current1_ok===true&&status.current2_ok===true&&Number.isFinite(status.current1)&&Number.isFinite(status.current2)?status.current1+status.current2:NaN;}
function electricalPower(status){var current=totalCurrent(status);return Number.isFinite(current)&&Number.isFinite(status.supply_voltage)&&status.supply_voltage>0?status.supply_voltage*current:NaN;}
function temperatureSlope(points,now){
 var recent=points.filter(function(point){return point.valid&&Number.isFinite(point.temperature)&&now-point.time<=30000;});
 if(recent.length<4||recent[recent.length-1].time-recent[0].time<8000)return NaN;
 var origin=recent[0].time,sumX=0,sumY=0,sumXY=0,sumXX=0;
 recent.forEach(function(point){var x=(point.time-origin)/60000,y=point.temperature;sumX+=x;sumY+=y;sumXY+=x*y;sumXX+=x*x;});
 var denominator=recent.length*sumXX-sumX*sumX;
 return denominator?((recent.length*sumXY-sumX*sumY)/denominator):NaN;
}
function estimateEtaMinutes(status,slope){
 if(status.state!=="AUFHEIZEN"||!Number.isFinite(status.temperature)||!Number.isFinite(status.setpoint)||!Number.isFinite(slope)||slope<=.05)return NaN;
 var remaining=status.setpoint-status.temperature,eta=remaining/slope;
 return remaining>.1&&eta>0&&eta<=120?eta:NaN;
}
function stepResponseMetrics(points,startTemperature,target,startTime,endTime){
 points=(points||[]).filter(function(point){return point&&point.valid&&Number.isFinite(point.temperature)&&point.time>=startTime&&point.time<=endTime;}).sort(function(a,b){return a.time-b.time;});
 var amplitude=target-startTemperature,result={valid:false,samples:points.length,progress:0,stage:"waiting",riseMs:NaN,t63Ms:NaN,settlingMs:NaN,overshoot:NaN,overshootPercent:NaN,steadyError:NaN,reached10:false,reached63:false,reached90:false,settled:false,modelHint:"NOCH KEINE AUSSAGE"};
 if(!Number.isFinite(startTemperature)||!Number.isFinite(target)||!Number.isFinite(amplitude)||amplitude<=.5||!points.length)return result;
 result.valid=true;
 function crossing(fraction){var threshold=startTemperature+amplitude*fraction;return points.find(function(point){return point.temperature>=threshold;});}
 var at10=crossing(.1),at63=crossing(.632),at90=crossing(.9),maximum=points.reduce(function(value,point){return Math.max(value,point.temperature);},-Infinity),tail=points.filter(function(point){return endTime-point.time<=30000;}),tolerance=Math.max(.2,Math.abs(amplitude)*.02),lastOutside=-1;if(!tail.length)tail=points.slice(-1);var tailAverage=tail.reduce(function(sum,point){return sum+point.temperature;},0)/tail.length;
 points.forEach(function(point,index){if(Math.abs(target-point.temperature)>tolerance)lastOutside=index;});
 var settlePoint=lastOutside<points.length-1?points[lastOutside+1]:null,settleDuration=settlePoint?endTime-settlePoint.time:0;
 result.reached10=!!at10;result.reached63=!!at63;result.reached90=!!at90;result.progress=clamp((points[points.length-1].temperature-startTemperature)/amplitude,0,1);result.riseMs=at10&&at90?at90.time-at10.time:NaN;result.t63Ms=at63?at63.time-startTime:NaN;result.overshoot=Math.max(0,maximum-target);result.overshootPercent=amplitude?result.overshoot/amplitude*100:NaN;result.steadyError=target-tailAverage;result.settled=!!settlePoint&&settleDuration>=15000&&result.reached90;result.settlingMs=result.settled?settlePoint.time-startTime:NaN;
 if(result.settled)result.stage="settled";else if(result.reached10)result.stage="running";
 if(points.length<6||endTime-startTime<10000||!result.reached63)result.modelHint="NOCH ZU WENIG MESSDATEN";else if(result.overshootPercent>5)result.modelHint="PT2 / VERZÖGERUNGEN PRÜFEN";else if(result.reached90)result.modelHint="PT1 ALS STARTMODELL PLAUSIBEL";else result.modelHint="PT1 / PT2 NOCH OFFEN";
 return result;
}
function setMilestone(id,done,current){var node=byId(id);if(!node)return;node.classList.toggle("done",!!done);node.classList.toggle("current",!!current);}
function renderStepResponse(now){
 var session=runtime.session||runtime.lastSession,points=[],startTime=NaN,endTime=now,startTemperature=NaN,target=NaN;
 if(session){startTime=session.startTime;endTime=session.endTime||now;startTemperature=session.startTemperature;target=session.target;points=history.filter(function(point){return point.time>=startTime&&point.time<=endTime;});}
 if(PREVIEW&&(!session||points.length<12)&&history.length>=12){points=history.slice();startTime=points[0].time;endTime=points[points.length-1].time;startTemperature=points[0].temperature;target=points[0].target;}
 var result=stepResponseMetrics(points,startTemperature,target,startTime,endTime),card=byId("stepResponseCard"),latest=points.length?points[points.length-1]:null;
 if(card)card.dataset.stage=result.stage;
 text("stepResponseState",result.stage==="settled"?"AUSGEREGELT":result.stage==="running"?"ERFASSUNG LÄUFT":"WARTE AUF START");
 text("stepRiseTime",responseTime(result.riseMs));text("stepT63",responseTime(result.t63Ms));text("stepOvershoot",Number.isFinite(result.overshoot)?fixed(result.overshoot)+" K · "+fixed(result.overshootPercent,1)+" %":"—");text("stepSettlingTime",responseTime(result.settlingMs));text("stepSteadyError",Number.isFinite(result.steadyError)?(result.steadyError>=0?"+":"")+fixed(result.steadyError)+" K":"—");text("stepModelHint",result.modelHint);
 var progress=byId("stepResponseProgress");if(progress)progress.style.width=clamp(result.progress,0,1)*100+"%";
 setMilestone("stepMilestoneStart",result.valid,result.valid&&!result.reached10);setMilestone("stepMilestone10",result.reached10,result.reached10&&!result.reached63);setMilestone("stepMilestone63",result.reached63,result.reached63&&!result.reached90);setMilestone("stepMilestone90",result.reached90,result.reached90&&!result.settled);setMilestone("stepMilestoneSettled",result.settled,result.settled);
 return{metrics:result,latest:latest};
}
function addEvent(message,tone){
 var last=runtime.events[0];
 if(last&&last.message===message&&Date.now()-last.time<1500)return;
 runtime.events.unshift({time:Date.now(),message:message,tone:tone||"normal"});
 runtime.events=runtime.events.slice(0,24);
 var list=byId("eventLog");
 if(list)list.innerHTML=runtime.events.slice(0,12).map(function(entry){return'<li class="'+entry.tone+'"><time>'+new Date(entry.time).toLocaleTimeString("de-DE")+'</time><span>'+entry.message+'</span></li>';}).join("");
}
function showRecovery(){var toast=byId("recoveryToast");if(!toast)return;toast.hidden=false;clearTimeout(runtime.recoveryTimer);runtime.recoveryTimer=setTimeout(function(){toast.hidden=true;},4000);}
function setOnline(value,message){
 var wasOnline=runtime.online,wasEver=runtime.everOnline;
 runtime.online=!!value;
 document.body.dataset.live=String(runtime.online);
 text("connectionState",runtime.online?"LIVE":"OFFLINE");
 if(runtime.online){
  runtime.everOnline=true;
  text("connectionTitle","Pico verbunden");text("connectionDetail","Live-Werte werden alle 500 ms aktualisiert.");
  if(!wasOnline&&wasEver){addEvent("Verbindung wiederhergestellt","recovery");showRecovery();}
 }else{
  text("connectionTitle",wasEver?"Verbindung unterbrochen":"Verbindung wird aufgebaut");
  text("connectionDetail",message||(wasEver?"Letzte Live-Daten sind als veraltet markiert.":"Warte auf eine Antwort des Pico."));
  if(wasOnline)addEvent("Verbindung zum Pico unterbrochen","fault");
  if(message)text("controlMessage",message);
 }
}
function hasUnlock(){if(runtime.token&&Date.now()<runtime.tokenExpires)return true;if(runtime.token){runtime.token="";runtime.tokenExpires=0;setUnlock(false,"Freigabe abgelaufen. PIN erneut eingeben.");}return false;}
function setUnlock(unlocked,message){document.body.classList.toggle("control-unlocked",unlocked);byId("controlActions").setAttribute("aria-hidden","false");text("lockIcon",unlocked?"🔓":"🔒");text("controlTitle",unlocked?"Steuerung freigegeben":"Steuerung gesperrt");text("controlMessage",message||(unlocked?"Freigabe endet automatisch nach fünf Minuten.":"Live-Werte bleiben ohne PIN sichtbar."));text("unlockButton",unlocked?"Freigabe erneuern":"Mit PIN freigeben");}
function safetyValue(name,value){return{name:name,value:value,label:value===true?"OK":value===false?"NICHT BEREIT":"NICHT VERFÜGBAR"};}
function safety(status){
 var active=status.state==="AUFHEIZEN"||status.state==="HALTEN",fault=status.state==="FEHLER"||status.fault!=="KEIN FEHLER",fanCheck=status.fault==="LUEFTER"?false:(status.power>0&&status.fan_supplied?status.fan_rpm>0:null);
 var checks=[safetyValue("Temperatur",status.sensor_ok),safetyValue("Sensorik",status.temp1_ok===null||status.temp2_ok===null||status.tla2024_ok===null?null:status.temp1_ok&&status.temp2_ok&&status.tla2024_ok),safetyValue("Strom",status.current_ok),safetyValue("Lüfter",fanCheck),safetyValue("Becher",status.cup),safetyValue("Versorgung",status.power_good),safetyValue("WLAN",status.wifi),safetyValue("Webserver",status.webserver_ready)];
 var known=checks.filter(function(check){return check.value!==null;}),ok=known.filter(function(check){return check.value===true;}).length,safe=!fault&&(status.start_allowed===true||active);
 byId("safetySummary").classList.toggle("fault",fault||(!active&&status.start_allowed===false));
 text("safetyTitle",fault?"START GESPERRT":safe?"SYSTEM OK":"START GESPERRT");
 text("safetyReason",fault?status.fault_description:active?"Alle Sicherheitsprüfungen der Firmware bleiben aktiv.":status.start_allowed===true?"Alle Freigaben bestätigt.":status.start_block_reason);
 text("healthSummary",ok+" / "+known.length+" reale Checks OK"+(known.length<checks.length?" · "+(checks.length-known.length)+" nicht bewertbar":""));
 byId("safetyDetails").innerHTML=checks.map(function(check){return'<span>'+check.name+': <b>'+check.label+'</b></span>';}).join("");
}
function hardwareState(status,id){
 var fault=status.fault,active=status.power>0;
 switch(id){
  case"pico":return runtime.online?["OK","API erreichbar","ok"]:["NICHT VERBUNDEN","Keine Live-API","warning"];
  case"oled":return status.display_initialized===true?["INITIALISIERT","SSD1306 bereit","normal"]:status.display_initialized===false?["NICHT VERFÜGBAR","Nicht initialisiert","inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"temp1":return status.temp1_ok===true?["OK",fixed(status.temperature1)+" °C","ok"]:status.temp1_ok===false?["FEHLER","Signal unplausibel","fault"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"temp2":return status.temp2_ok===true?["OK",fixed(status.temperature2)+" °C","ok"]:status.temp2_ok===false?["NICHT VERFÜGBAR","Kein gültiges Signal","inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"adc":return status.tla2024_ok===true?["OK","I²C-ADC verfügbar","ok"]:status.tla2024_ok===false?["NICHT VERBUNDEN","TLA2024 fehlt","warning"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"light":return status.light_ok===true?["OK",Math.round(status.light_level*100)+" % · "+(status.night?"Nachtmodus":"Tagmodus"),"ok"]:status.light_ok===false?["NICHT VERFÜGBAR","Kein gültiger Messwert","inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"fan":return fault==="LUEFTER"?["FEHLER","Tachosignal unplausibel","fault"]:status.fan_supplied&&status.fan_rpm>0?["AKTIV",fixed(status.fan_rpm,0)+" rpm","active"]:status.fan_supplied?["AUS","0 rpm","inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"tacho":return fault==="LUEFTER"?["FEHLER","Kein plausibles Signal","fault"]:status.fan_supplied&&status.fan_rpm>0?["OK",fixed(status.fan_rpm,0)+" rpm","ok"]:status.fan_supplied?["AUS","Im Stillstand nicht prüfbar","inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"peltier1":case"peltier2":return status.power_supplied?(active?["AKTIV",fixed(status.power,0)+" %","active"]:["AUS","PWM 0 %","inactive"]):["UNBEKANNT","Kein API-Wert","warning"];
  case"current1":return status.current1_ok===true?["OK",fixed(status.current1,2)+" A","ok"]:status.current1_ok===false?[fault==="UEBERSTROM"||fault==="STROMSENSOR"?"FEHLER":"NICHT VERFÜGBAR","Kein gültiger Messwert",fault==="UEBERSTROM"||fault==="STROMSENSOR"?"fault":"inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"current2":return status.current2_ok===true?["OK",fixed(status.current2,2)+" A","ok"]:status.current2_ok===false?[fault==="UEBERSTROM"||fault==="STROMSENSOR"?"FEHLER":"NICHT VERFÜGBAR","Kein gültiger Messwert",fault==="UEBERSTROM"||fault==="STROMSENSOR"?"fault":"inactive"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"cup":return status.cup===true?["AKTIV","Becher erkannt","active"]:status.cup===false?["NICHT VERBUNDEN","Kein Becher erkannt","warning"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"power":return status.power_good===true?["OK","Power-Good aktiv","ok"]:status.power_good===false?["NICHT VERBUNDEN","Leistungsfreigabe fehlt","warning"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"rgb":return status.leds_initialized===true?["INITIALISIERT","Statusausgänge bereit","normal"]:status.leds_initialized===false?["NICHT VERFÜGBAR","Nicht initialisiert","inactive"]:["UNBEKANNT","Nicht separat überwacht","warning"];
  case"wifi":return status.wifi===true?["OK",status.wifi_ssid+" · "+status.wifi_ip,"ok"]:status.wifi===false?["NICHT VERBUNDEN","WLAN getrennt","warning"]:["UNBEKANNT","Kein API-Wert","warning"];
  case"webserver":return status.webserver_ready===true?["OK","HTTP bereit","ok"]:status.webserver_ready===false?["NICHT VERBUNDEN","HTTP nicht bereit","warning"]:["UNBEKANNT","Kein API-Wert","warning"];
 }
 return["UNBEKANNT","Nicht direkt überwacht","warning"];
}
var hardwareItems=[["pico","Raspberry Pi Pico W"],["oled","OLED"],["temp1","TMP36 Sensor 1"],["temp2","TMP36 Sensor 2"],["adc","TLA2024 ADC"],["light","Lichtsensor"],["fan","Lüfter"],["tacho","Lüfter-Tacho"],["peltier1","Peltier 1"],["peltier2","Peltier 2"],["current1","Strommessung P1"],["current2","Strommessung P2"],["cup","Cup Detector"],["power","Power-Good"],["rgb","RGB / Statusring"],["wifi","WLAN"],["webserver","Webserver"]];
function buildHardwareGrid(){var grid=byId("hardwareGrid");grid.innerHTML=hardwareItems.map(function(item){return'<article class="hardware-item" data-hardware="'+item[0]+'"><i></i><span><strong>'+item[1]+'</strong><small>Warte auf Live-Daten</small></span><b>UNBEKANNT</b></article>';}).join("");}
function renderHardware(status){hardwareItems.forEach(function(item){var node=document.querySelector('[data-hardware="'+item[0]+'"]'),result=hardwareState(status,item[0]);if(!node)return;node.dataset.tone=result[2];node.querySelector("b").textContent=result[0];node.querySelector("small").textContent=result[1];});}
function startSession(status,now){runtime.session={startTime:now,startTemperature:status.temperature,target:status.setpoint,maxPower:status.power,maxError:Math.abs(status.error),maxTemperature:status.temperature,holdingAt:status.state==="HALTEN"?now:0,endTime:0,energyWh:0,energyAvailable:Number.isFinite(electricalPower(status)),lastEnergyAt:now,lastPowerW:electricalPower(status)};addEvent("Browser-Sessionerfassung gestartet","active");}
function updateSession(status,now){
 var active=status.state==="AUFHEIZEN"||status.state==="HALTEN",wasActive=runtime.previous&&(runtime.previous.state==="AUFHEIZEN"||runtime.previous.state==="HALTEN");
 if(active&&!runtime.session)startSession(status,now);
 if(runtime.session){
  var session=runtime.session,powerW=electricalPower(status),dt=Math.min(5000,Math.max(0,now-session.lastEnergyAt));
  session.maxPower=Math.max(session.maxPower,number(status.power,0));session.maxError=Math.max(session.maxError,Math.abs(number(status.error,0)));session.maxTemperature=Math.max(session.maxTemperature,number(status.temperature,session.maxTemperature));
  if(status.state==="HALTEN"&&!session.holdingAt)session.holdingAt=now;
  if(session.energyAvailable&&Number.isFinite(powerW)&&Number.isFinite(session.lastPowerW))session.energyWh+=(session.lastPowerW+powerW)/2*dt/3600000;else if(!Number.isFinite(powerW))session.energyAvailable=false;
  session.lastEnergyAt=now;session.lastPowerW=powerW;
  if(!active&&wasActive){session.endTime=now;runtime.lastSession=session;runtime.session=null;addEvent("Heizsession beendet");}
 }
 renderSession(runtime.session||runtime.lastSession,now);
}
function renderSession(session,now){
 if(!session){text("sessionStatus","NOCH KEINE SESSION");return;}
 var end=session.endTime||now,overshoot=Math.max(0,session.maxTemperature-session.target);
 text("sessionStatus",session.endTime?"ABGESCHLOSSEN":session.holdingAt?"HOLDING":"LÄUFT");text("sessionStart",fixed(session.startTemperature)+" °C · "+new Date(session.startTime).toLocaleTimeString("de-DE"));text("sessionTarget",fixed(session.target)+" °C");text("sessionTargetTime",session.holdingAt?duration(session.holdingAt-session.startTime):"NOCH NICHT ERREICHT");text("sessionMaxPower",fixed(session.maxPower,0)+" %");text("sessionMaxError",fixed(session.maxError)+" K");text("sessionOvershoot",fixed(overshoot)+" K");text("sessionEnergy",session.energyAvailable?fixed(session.energyWh,2)+" Wh":"NICHT VERFÜGBAR");text("sessionDuration",duration(end-session.startTime));
}
function trackTransitions(status){
 var previous=runtime.previous;
 if(!previous){addEvent(status.uptime_ms>0&&status.uptime_ms<15000?"System gestartet":"Live-Verbindung hergestellt","recovery");if(status.state!=="AUS")addEvent("Systemzustand: "+status.state);runtime.previous=status;return;}
 if(previous.state!==status.state){
  if(status.state==="BEREIT")addEvent("READY · System bereit","recovery");
  else if(status.state==="AUFHEIZEN")addEvent("HEATING · Aufheizen aktiv","active");
  else if(status.state==="HALTEN")addEvent("HOLDING · Solltemperatur erreicht","recovery");
  else if(status.state==="FEHLER")addEvent("ERROR · "+status.fault_description,"fault");
  else if(status.state==="AUS")addEvent("STOP · Heizleistung aus");
 }
 if(previous.setpoint!==status.setpoint)addEvent("Sollwert geändert: "+fixed(status.setpoint)+" °C");
 if(previous.cup!==status.cup&&status.cup!==null)addEvent(status.cup?"Becher erkannt":"Becher entfernt",status.cup?"recovery":"fault");
 if(previous.power_good!==status.power_good&&status.power_good!==null)addEvent(status.power_good?"Power-Good wieder aktiv":"Power-Good verloren",status.power_good?"recovery":"fault");
 if(previous.wifi!==status.wifi&&status.wifi!==null)addEvent(status.wifi?"WLAN verbunden":"WLAN getrennt",status.wifi?"recovery":"fault");
 if(previous.fault!==status.fault){if(status.fault!=="KEIN FEHLER")addEvent(status.fault_description,"fault");else addEvent("Fehlerzustand aufgehoben","recovery");}
 runtime.previous=status;
}
function derivedMetrics(status,now){
 var delta=deltaTemperature(status),current=totalCurrent(status),powerW=electricalPower(status),slope=temperatureSlope(history,now),eta=estimateEtaMinutes(status,slope),session=runtime.session||runtime.lastSession;
 text("metricDeltaT",Number.isFinite(delta)?(delta>=0?"+":"")+fixed(delta)+" K":"NICHT VERFÜGBAR");text("techDeltaT",Number.isFinite(delta)?(delta>=0?"+":"")+fixed(delta)+" K":"NICHT VERFÜGBAR");
 text("metricSlope",Number.isFinite(slope)?(slope>=0?"+":"")+fixed(slope,2)+" °C/min":"NICHT VERFÜGBAR");
 text("metricEta",Number.isFinite(eta)?"ca. "+duration(eta*60000)+" bis Soll":"PROGNOSE NICHT VERFÜGBAR");
 text("metricCurrent",Number.isFinite(current)?fixed(current,2)+" A":"NICHT VERFÜGBAR");text("heroCurrent",Number.isFinite(current)?fixed(current,2)+" A":"—");text("techTotalCurrent",Number.isFinite(current)?fixed(current,2)+" A":"NICHT VERFÜGBAR");
 text("metricElectricalPower",Number.isFinite(powerW)?fixed(powerW,1)+" W":"NICHT VERFÜGBAR");text("metricEnergy",session&&session.energyAvailable?fixed(session.energyWh,2)+" Wh":"NICHT VERFÜGBAR");
 var points=history.filter(function(point){return now-point.time<=runtime.range*1000&&point.valid&&point.validTarget;}),maxError=points.length?points.reduce(function(max,point){return Math.max(max,Math.abs(point.target-point.temperature));},0):NaN;
 text("chartMaxError",Number.isFinite(maxError)?fixed(maxError)+" K":"—");text("chartHeatingTime",runtime.session?duration(now-runtime.session.startTime):runtime.lastSession?duration((runtime.lastSession.holdingAt||runtime.lastSession.endTime)-runtime.lastSession.startTime):"—");text("chartHoldingTime",runtime.session&&runtime.session.holdingAt?duration(now-runtime.session.holdingAt):runtime.lastSession&&runtime.lastSession.holdingAt?duration(runtime.lastSession.endTime-runtime.lastSession.holdingAt):"—");
 renderStepResponse(now);
}
function render(input,options){
 var status=normalize(input),record=!options||options.record!==false,now=Date.now();runtime.current=status;document.body.dataset.state=status.state;document.body.dataset.cup=status.cup===true?"present":status.cup===false?"absent":"unknown";
 var active=status.state==="AUFHEIZEN"||status.state==="HALTEN",temperatureOk=status.sensor_ok===true&&Number.isFinite(status.temperature),current=totalCurrent(status),rawOutput=Number.isFinite(status.p_term)&&Number.isFinite(status.i_term)?status.p_term+status.i_term:NaN;
 text("systemState",status.state);text("liveSystemState",status.state);text("actualTemperature",temperatureOk?fixed(status.temperature):"—");text("liveTemperature",temperatureOk?fixed(status.temperature):"—");text("sensorQuality",temperatureOk?(status.night?"Nachtmodus · Sensor plausibel":"Sensor plausibel"):(status.sensor_ok===false?"Sensorfehler":"Messwert nicht verfügbar"));
 text("heroSetpoint",fixed(status.setpoint));text("heroDeviation",Number.isFinite(status.error)?(status.error>=0?"+":"")+fixed(status.error)+" K":"—");text("heroPower",status.power_supplied?fixed(status.power,0)+" %":"—");text("heroFan",status.fan_supplied?fixed(status.fan_rpm,0)+" rpm":"—");text("heroCurrent",Number.isFinite(current)?fixed(current,2)+" A":"—");
 text("liveSetpoint",fixed(status.setpoint));text("powerOutput",status.power_supplied?fixed(status.power,0)+" %":"—");text("fanRpm",status.fan_supplied?fixed(status.fan_rpm,0)+" rpm":"—");
 text("loopSetpoint",fixed(status.setpoint)+" °C");text("loopDeviation",Number.isFinite(status.error)?(status.error>=0?"+":"")+fixed(status.error)+" K":"—");text("piNodeState",active?"REGELT":"BEREIT");text("loopPiParts","P "+fixed(status.p_term)+" % · I "+fixed(status.i_term)+" %");text("loopOutput",status.power_supplied?fixed(status.power,0)+" %":"—");text("loopPeltierState",status.power_supplied?(status.power>0?"AKTIV · NUR HEIZEN":"AUS"):"UNBEKANNT");text("loopSensor",temperatureOk?fixed(status.temperature)+" °C":"—");text("plantState",status.cup===false?"Kein Becher erkannt":active?(status.state==="HALTEN"?"hält Temperatur":"wird erwärmt"):"Regelstrecke");
 text("analysisRegulatorState",status.state==="FEHLER"?"PI · GESPERRT":active?"PI · REGELT":"PI · BEREIT");text("analysisError",Number.isFinite(status.error)?(status.error>=0?"+":"")+fixed(status.error)+" K":"—");text("analysisP",Number.isFinite(status.p_term)?fixed(status.p_term)+" %":"—");text("analysisI",Number.isFinite(status.i_term)?fixed(status.i_term)+" %":"—");text("analysisRaw",Number.isFinite(rawOutput)?fixed(rawOutput)+" %":"—");text("analysisOutput",status.power_supplied?fixed(status.power,0)+" %":"—");text("analysisPMeterValue",Number.isFinite(status.p_term)?fixed(status.p_term)+" %":"—");text("analysisIMeterValue",Number.isFinite(status.i_term)?fixed(status.i_term)+" %":"—");text("analysisOutputMeterValue",status.power_supplied?fixed(status.power,0)+" %":"—");meter("analysisPMeter",status.p_term);meter("analysisIMeter",status.i_term);meter("analysisOutputMeter",status.power);text("analysisKp",fixed(status.kp,3));text("analysisKi",fixed(status.ki,3));text("analysisAntiWindup",boolLabel(status.anti_windup,"AKTIV","INAKTIV"));text("analysisCycle",Number.isFinite(status.control_period_ms)?fixed(status.control_period_ms,0)+" ms":"—");var limitState=byId("analysisLimitState");if(limitState){limitState.textContent=boolLabel(status.output_limited,"AKTIV","INAKTIV");limitState.parentElement.classList.toggle("limited",status.output_limited===true);}
 text("controllerTrendState",runtime.online?(active?"LIVE · REGELT":"LIVE · "+status.state):"OFFLINE");text("trendErrorValue",Number.isFinite(status.error)?(status.error>=0?"+":"")+fixed(status.error)+" K":"—");text("trendPValue",Number.isFinite(status.p_term)?fixed(status.p_term)+" %":"—");text("trendIValue",Number.isFinite(status.i_term)?fixed(status.i_term)+" %":"—");text("trendOutputValue",status.power_supplied?fixed(status.power,0)+" %":"—");
 text("techKp",fixed(status.kp,3));text("techKi",fixed(status.ki,3));text("techError",Number.isFinite(status.error)?fixed(status.error)+" K":"NICHT VERFÜGBAR");text("techP",Number.isFinite(status.p_term)?fixed(status.p_term)+" %":"NICHT VERFÜGBAR");text("techI",Number.isFinite(status.i_term)?fixed(status.i_term)+" %":"NICHT VERFÜGBAR");text("techRawOutput",Number.isFinite(rawOutput)?fixed(rawOutput)+" %":"NICHT VERFÜGBAR");text("techLimitedOutput",status.power_supplied?fixed(status.power)+" %":"NICHT VERFÜGBAR");text("techAntiWindup",boolLabel(status.anti_windup,"AKTIV","INAKTIV"));text("techOutputLimit",boolLabel(status.output_limited,"AKTIV","INAKTIV"));text("techCycle",Number.isFinite(status.control_period_ms)?fixed(status.control_period_ms,0)+" ms":"NICHT VERFÜGBAR");text("techMaxTemp",fixed(status.max_safe_temperature)+" °C");
 text("techTemp1",status.temp1_ok===true?fixed(status.temperature1)+" °C":"NICHT VERFÜGBAR");text("techTemp2",status.temp2_ok===true?fixed(status.temperature2)+" °C":"NICHT VERFÜGBAR");text("techCurrent1",status.current1_ok===true?fixed(status.current1,2)+" A":"NICHT VERFÜGBAR");text("techCurrent2",status.current2_ok===true?fixed(status.current2,2)+" A":"NICHT VERFÜGBAR");text("techLight",status.light_ok===true?Math.round(status.light_level*100)+" %":"NICHT VERFÜGBAR");text("techNight",boolLabel(status.night,"AKTIV","TAGMODUS"));text("techPowerGood",boolLabel(status.power_good,"OK","NICHT VERBUNDEN"));text("techCup",boolLabel(status.cup,"BECHER ERKANNT","KEIN BECHER"));
 text("networkName",status.wifi_ssid);text("networkIp",status.wifi_ip);text("techWebserver",boolLabel(status.webserver_ready,"BEREIT","NICHT BEREIT"));text("techUptime",status.uptime_ms?duration(status.uptime_ms):"—");text("lastSignal",runtime.lastUpdate?new Date(runtime.lastUpdate).toLocaleTimeString("de-DE"):"—");
 text("startBlockReason",status.start_allowed===true&&!active?"START freigegeben · alle Firmware-Prüfungen bestätigt":status.start_block_reason);byId("startBlockReason").className="start-reason "+(status.start_allowed===true&&!active?"allowed":"blocked");
 if(!runtime.targetDraft&&document.activeElement!==byId("targetInput"))byId("targetInput").value=fixed(status.setpoint);
 var controls=runtime.online&&hasUnlock();byId("targetDown").disabled=!controls;byId("targetUp").disabled=!controls;byId("targetInput").disabled=!controls;byId("setpointButton").disabled=!controls;byId("startButton").disabled=!controls||status.start_allowed!==true||active;byId("stopButton").disabled=!runtime.online||!active;
 byId("visualStage").classList.toggle("fan-active",status.fan_supplied&&status.fan_percent>0);document.documentElement.style.setProperty("--fan-period",status.fan_percent>0?Math.max(2.6,8-status.fan_percent*.05)+"s":"8s");
 if(record){addHistory(status);updateSession(status,now);trackTransitions(status);}else renderSession(runtime.session||runtime.lastSession,now);derivedMetrics(status,now);safety(status);renderHardware(status);if(window.V4Twin)window.V4Twin.update(status,runtime.online);
}
async function fetchWithTimeout(url,options){var controller=new AbortController(),timer=setTimeout(function(){controller.abort();},1800);try{return await fetch(url,Object.assign({cache:"no-store",signal:controller.signal},options||{}));}finally{clearTimeout(timer);}}
async function poll(){if(PREVIEW||runtime.busy)return;runtime.busy=true;try{var response=await fetchWithTimeout("/api/status");if(!response.ok)throw new Error("HTTP "+response.status);var data=await response.json();runtime.lastUpdate=Date.now();setOnline(true);render(data);}catch(error){setOnline(false,"API nicht erreichbar · letztes Update "+relativeUpdate());if(runtime.current)render(runtime.current,{record:false});}finally{runtime.busy=false;}}
async function unlock(pin){if(PREVIEW&&window.PreviewDriver){var simulated=window.PreviewDriver.unlock(pin);if(!simulated.ok)throw new Error(simulated.reason);runtime.token=simulated.token;runtime.tokenExpires=Date.now()+simulated.expires_in_ms;setUnlock(true);return;}var response=await fetchWithTimeout("/api/unlock",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:"pin="+encodeURIComponent(pin)}),result=await response.json().catch(function(){return{};});if(!response.ok)throw new Error(result.reason||"Freigabe abgelehnt");runtime.token=result.token;runtime.tokenExpires=Date.now()+number(result.expires_in_ms,300000);setUnlock(true);}
async function command(path,requiresToken){if(!runtime.online||(requiresToken!==false&&!hasUnlock()))return false;var token=requiresToken===false?"":runtime.token;if(PREVIEW&&window.PreviewDriver){window.PreviewDriver.command(path,token);if(path==="start")addEvent("START gedrückt");else if(path==="stop")addEvent("STOP gedrückt");return true;}try{var response=await fetchWithTimeout("/api/"+path,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:token?"token="+encodeURIComponent(token):""}),result=await response.json().catch(function(){return{};});if(response.status===401){runtime.token="";setUnlock(false,"Freigabe abgelaufen. PIN erneut eingeben.");throw new Error("Steuerung gesperrt");}if(!response.ok)throw new Error(result.reason||"Befehl abgelehnt");if(path==="start")addEvent("START vom Pico bestätigt");else if(path==="stop")addEvent("STOP vom Pico bestätigt");await poll();return true;}catch(error){text("controlMessage",error.message);return false;}}
function adjust(delta){var value=clamp(number(String(byId("targetInput").value).replace(",","."),45)+delta,20,60);byId("targetInput").value=fixed(value);runtime.targetDraft=true;}
async function setpoint(){var value=clamp(number(String(byId("targetInput").value).replace(",","."),45),20,60);if(await command("setpoint?value="+value.toFixed(1),true)){runtime.targetDraft=false;byId("targetInput").value=fixed(value);}}
function addHistory(status){var now=Date.now(),point={time:now,temperature:status.temperature,temperature2:status.temperature2,target:status.setpoint,power:status.power,error:status.error,pTerm:status.p_term,iTerm:status.i_term,rawOutput:Number.isFinite(status.p_term)&&Number.isFinite(status.i_term)?status.p_term+status.i_term:NaN,current1:status.current1,current2:status.current2,fan:status.fan_rpm,light:status.light_level,valid:status.sensor_ok===true,valid2:status.temp2_ok===true,validTarget:status.setpoint_supplied,validPower:status.power_supplied,validController:Number.isFinite(status.error)&&Number.isFinite(status.p_term)&&Number.isFinite(status.i_term)&&status.power_supplied,validCurrent1:status.current1_ok===true,validCurrent2:status.current2_ok===true,validFan:status.fan_supplied,validLight:status.light_ok===true};if(history.length&&now-history[history.length-1].time<400)history[history.length-1]=point;else history.push(point);while(history.length&&now-history[0].time>MAX_HISTORY_SECONDS*1000)history.shift();scheduleChart();}
function scheduleChart(){if(runtime.drawQueued)return;runtime.drawQueued=true;requestAnimationFrame(function(){runtime.drawQueued=false;drawChart();drawControllerTrend();});}
function controllerWindowSeconds(now){var session=runtime.session||runtime.lastSession,age=session&&Number.isFinite(session.startTime)?(now-session.startTime)/1000:0;if(PREVIEW&&history.length>1)age=Math.max(age,(history[history.length-1].time-history[0].time)/1000);return clamp(Math.ceil(Math.max(CONTROLLER_HISTORY_SECONDS,age)/300)*300,CONTROLLER_HISTORY_SECONDS,MAX_HISTORY_SECONDS);}
function drawChart(){var canvas=byId("timelineCanvas"),rect=canvas.getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2),width=Math.max(320,Math.round(rect.width)),height=Math.max(220,Math.round(rect.height));if(canvas.width!==width*scale||canvas.height!==height*scale){canvas.width=width*scale;canvas.height=height*scale;}var context=canvas.getContext("2d");context.setTransform(scale,0,0,scale,0,0);context.clearRect(0,0,width,height);var pad={left:48,right:42,top:24,bottom:32},plotW=width-pad.left-pad.right,plotH=height-pad.top-pad.bottom,now=Date.now(),start=now-runtime.range*1000,points=history.filter(function(point){return point.time>=start;});context.strokeStyle="#303631";context.lineWidth=1;context.fillStyle="#878d87";context.font="11px Segoe UI";for(var i=0;i<=4;i++){var y=pad.top+plotH*i/4;context.beginPath();context.moveTo(pad.left,y);context.lineTo(width-pad.right,y);context.stroke();context.fillText(String(60-i*15)+"°",8,y+4);}function draw(key,valid,color,min,max,dash){if(!runtime.signals[key]||points.length<2)return;context.beginPath();var started=false;points.forEach(function(point){if(!point[valid]||!Number.isFinite(point[key])){started=false;return;}var x=pad.left+clamp((point.time-start)/(runtime.range*1000),0,1)*plotW,y=pad.top+(1-clamp((point[key]-min)/(max-min),0,1))*plotH;if(!started){context.moveTo(x,y);started=true;}else context.lineTo(x,y);});context.strokeStyle=color;context.lineWidth=2;context.setLineDash(dash||[]);context.stroke();context.setLineDash([]);}draw("temperature","valid","#76aec4",0,60);draw("target","validTarget","#d8ddd6",0,60,[7,6]);draw("power","validPower","#ed8549",0,100);draw("temperature2","valid2","#7bb1a0",0,60);draw("current1","validCurrent1","#d2a66d",0,8);draw("current2","validCurrent2","#b58cc2",0,8);draw("fan","validFan","#8b93ce",0,5000);draw("light","validLight","#d3c769",0,1);context.fillStyle="#878d87";context.fillText("−"+Math.round(runtime.range/60)+" min",pad.left,height-9);context.textAlign="right";context.fillText("jetzt",width-pad.right,height-9);context.textAlign="left";}
function drawControllerTrend(){
 var canvas=byId("controllerTrendCanvas");if(!canvas)return;var rect=canvas.getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2),width=Math.max(280,Math.round(rect.width)),height=Math.max(210,Math.round(rect.height));if(canvas.width!==width*scale||canvas.height!==height*scale){canvas.width=width*scale;canvas.height=height*scale;}var context=canvas.getContext("2d");context.setTransform(scale,0,0,scale,0,0);context.clearRect(0,0,width,height);
 var pad={left:42,right:46,top:18,bottom:28},plotW=width-pad.left-pad.right,plotH=height-pad.top-pad.bottom,now=Date.now(),windowSeconds=controllerWindowSeconds(now),start=now-windowSeconds*1000,points=history.filter(function(point){return point.time>=start&&point.validController;}),maxError=points.reduce(function(maximum,point){return Math.max(maximum,Math.abs(point.error));},0),errorScale=Math.max(5,Math.ceil(maxError/5)*5);
 text("controllerTrendSamples",String(points.length));text("controllerTrendWindow",Math.round(windowSeconds/60)+" min");context.font="9px Segoe UI";context.lineWidth=1;for(var i=0;i<=4;i++){var y=pad.top+plotH*i/4;context.strokeStyle="#2d342f";context.beginPath();context.moveTo(pad.left,y);context.lineTo(width-pad.right,y);context.stroke();context.fillStyle="#788079";context.textAlign="right";context.fillText(String(100-i*25)+" %",pad.left-6,y+3);context.textAlign="left";context.fillText((errorScale-i*errorScale/2>=0?"+":"")+fixed(errorScale-i*errorScale/2,0)+" K",width-pad.right+6,y+3);}
 function draw(key,color,min,max,widthValue,dash){if(points.length<2)return;context.beginPath();var started=false;points.forEach(function(point){if(!Number.isFinite(point[key])){started=false;return;}var x=pad.left+clamp((point.time-start)/(windowSeconds*1000),0,1)*plotW,y=pad.top+(1-clamp((point[key]-min)/(max-min),0,1))*plotH;if(!started){context.moveTo(x,y);started=true;}else context.lineTo(x,y);});context.strokeStyle=color;context.lineWidth=widthValue||2;context.setLineDash(dash||[]);context.stroke();context.setLineDash([]);}
 draw("pTerm","#ed8549",0,100,2);draw("iTerm","#d8b279",0,100,2);draw("power","#76aec4",0,100,2.5);draw("error","#71c393",-errorScale,errorScale,2,[5,4]);
 context.fillStyle="#788079";context.textAlign="left";context.fillText("−"+Math.round(windowSeconds/60)+" min",pad.left,height-8);context.textAlign="right";context.fillText("jetzt",width-pad.right,height-8);context.textAlign="left";
 if(points.length<2){context.fillStyle="#8b938c";context.font="12px Segoe UI";context.textAlign="center";context.fillText("Reglersignale werden mit der nächsten Live-Session aufgezeichnet.",width/2,height/2);context.textAlign="left";}
}
function setPresentation(enabled){document.body.classList.toggle("presentation-mode",enabled);byId("presentationButton").setAttribute("aria-pressed",String(enabled));text("presentationButton",enabled?"BEENDEN":"PRÄSENTIEREN");byId("presentationButton").setAttribute("aria-label",enabled?"Präsentationsmodus schließen":"Präsentationsmodus öffnen");if(enabled&&document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(function(){});else if(!enabled&&document.fullscreenElement)document.exitFullscreen().catch(function(){});setTimeout(scheduleChart,100);}
function interactions(){
 byId("moreSignalsButton").addEventListener("click",function(){var open=byId("moreSignals").hidden;byId("moreSignals").hidden=!open;this.setAttribute("aria-expanded",String(open));this.textContent=open?"Weniger Messwerte":"Mehr Messwerte";});
 byId("safetyDetailsButton").addEventListener("click",function(){var open=byId("safetyDetails").hidden;byId("safetyDetails").hidden=!open;this.setAttribute("aria-expanded",String(open));});
 all("[data-signal]").forEach(function(button){button.addEventListener("click",function(){var key=button.dataset.signal;runtime.signals[key]=!runtime.signals[key];button.classList.toggle("active",runtime.signals[key]);scheduleChart();});});
 all("[data-range]").forEach(function(button){button.addEventListener("click",function(){runtime.range=number(button.dataset.range,60);all("[data-range]").forEach(function(item){item.classList.toggle("active",item===button);});scheduleChart();});});
 byId("unlockButton").addEventListener("click",function(){text("pinError","");byId("pinInput").value="";byId("unlockDialog").showModal();setTimeout(function(){byId("pinInput").focus();},50);});byId("unlockClose").addEventListener("click",function(){byId("unlockDialog").close();});byId("unlockForm").addEventListener("submit",async function(event){event.preventDefault();try{await unlock(byId("pinInput").value);byId("unlockDialog").close();if(runtime.current)render(runtime.current,{record:false});}catch(error){text("pinError",error.message);}});
 byId("targetDown").addEventListener("click",function(){adjust(-.5);});byId("targetUp").addEventListener("click",function(){adjust(.5);});byId("targetInput").addEventListener("input",function(){runtime.targetDraft=true;});byId("setpointButton").addEventListener("click",setpoint);byId("startButton").addEventListener("click",function(){command("start",true);});byId("stopButton").addEventListener("click",function(){command("stop",false);});
 byId("presentationButton").addEventListener("click",function(){setPresentation(!document.body.classList.contains("presentation-mode"));});document.addEventListener("fullscreenchange",function(){if(!document.fullscreenElement&&document.body.classList.contains("presentation-mode"))setPresentation(false);});
 addEventListener("resize",scheduleChart,{passive:true});
}
function relativeUpdate(){if(!runtime.lastUpdate)return"noch nie erfolgreich";var seconds=Math.max(0,Math.round((Date.now()-runtime.lastUpdate)/1000));return"vor "+seconds+" s";}
function boot(){buildHardwareGrid();interactions();if(window.V4Twin)window.V4Twin.initialise({preview:PREVIEW});if(PREVIEW&&window.PreviewDriver){document.body.classList.add("preview-mode");window.PreviewDriver.start();unlock("").then(function(){setUnlock(true,"Lokale Vorschau · Sollwert, START und STOPP ändern nur Demo-Daten.");if(runtime.current)render(runtime.current,{record:false});});}else{poll();setInterval(poll,POLL_MS);}if("scrollRestoration" in window.history)window.history.scrollRestoration="manual";setInterval(function(){if(!hasUnlock()&&document.body.classList.contains("control-unlocked"))setUnlock(false);if(!runtime.online){text("connectionDetail",runtime.everOnline?"Letztes erfolgreiches Update "+relativeUpdate()+" · Werte sind veraltet.":"Warte auf eine Antwort des Pico.");}if(runtime.session)renderSession(runtime.session,Date.now());},1000);}
addEventListener("load",function(){var review=new URLSearchParams(location.search).get("review"),id={product:"aufbau",loop:"regelkreis",analysis:"controllerAnalysis",dynamics:"controllerDynamics",live:"live",engineering:"technik"}[review];if(review==="presentation")setTimeout(function(){setPresentation(true);},300);else if(id)setTimeout(function(){if(review==="engineering")byId("engineeringDrawer").open=true;var old=document.documentElement.style.scrollBehavior,target=byId(id),offset=review==="dynamics"?84:0;document.documentElement.style.scrollBehavior="auto";scrollTo(0,scrollY+target.getBoundingClientRect().top-offset);document.documentElement.style.scrollBehavior=old;},460);},{once:true});
window.V3Metrics={deltaTemperature:deltaTemperature,totalCurrent:totalCurrent,electricalPower:electricalPower,temperatureSlope:temperatureSlope,estimateEtaMinutes:estimateEtaMinutes,stepResponseMetrics:stepResponseMetrics};
window.V3UI={acceptStatus:function(status,isOnline){if(isOnline!==false)runtime.lastUpdate=Date.now();setOnline(isOnline!==false);render(status,{record:isOnline!==false});},history:history,runtime:runtime,scheduleChart:scheduleChart,render:render,addEvent:addEvent,setPresentation:setPresentation};window.V4UI=window.V3UI;
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
