(function(){
"use strict";
var base={state:"AUFHEIZEN",fault:"KEIN FEHLER",fault_description:"Keine aktive Störung",temperature:32.4,temperature1:32.4,temperature2:31.8,setpoint:45,error:12.6,power:68,fan_rpm:1850,fan_percent:64,current1:2.8,current2:2.7,light_level:.72,sensor_ok:true,temp1_ok:true,temp2_ok:true,current_ok:true,current1_ok:true,current2_ok:true,tla2024_ok:true,light_ok:true,display_initialized:true,leds_initialized:true,cup:true,power_good:true,wifi:true,webserver_ready:true,wifi_ssid:"Obi W-lan Kenobi",wifi_ip:"10.78.252.72",night:false,start_allowed:false,start_block_reason:"Heizvorgang bereits aktiv",kp:5.2,ki:.075,p_term:65.5,i_term:2.5,output_limited:false,anti_windup:true,control_period_ms:250,max_safe_temperature:65,uptime_ms:438000};
var demo=Object.assign({},base),scenario="heating",automatic=false,started=performance.now(),last=started,simMinutes=0;
var profiles={
 full:["cup","temp1","temp2","plate","peltier1","peltier2","fan","pico","adc","current1","current2","light","oled","rgb","leds","buttons","power","wifi","webserver"],
 minimal:["cup","temp1","plate","peltier1","fan","pico","oled","buttons","power","wifi","webserver"],
 partial:["cup","temp1","plate","peltier1","peltier2","fan","pico","adc","current1","oled","leds","buttons","power","wifi","webserver"],
 noSensors:["plate","peltier1","peltier2","fan","pico","oled","rgb","leds","buttons","power","wifi","webserver"]
};
function derived(){demo.error=demo.setpoint-demo.temperature;demo.temperature1=demo.temperature;demo.temperature2=demo.temperature-.6+Math.sin(performance.now()/4500)*.08;demo.fan_percent=demo.power>0?Math.max(35,Math.round(demo.power*.82)):0;demo.fan_rpm=demo.fan_percent?Math.round(760+demo.fan_percent*19.5):0;demo.current1=demo.power*.0412;demo.current2=demo.power*.0397;demo.p_term=Math.max(0,demo.error*demo.kp);demo.i_term=Math.max(0,demo.power-demo.p_term);demo.uptime_ms+=500;}
function nominal(){Object.assign(demo,base,{fault:"KEIN FEHLER",fault_description:"Keine aktive Störung",sensor_ok:true,temp1_ok:true,temp2_ok:true,current_ok:true,current1_ok:true,current2_ok:true,tla2024_ok:true,cup:true,power_good:true,wifi:true,webserver_ready:true});}
function useProfile(profile){if(window.V4Twin&&window.V4Twin.setConnected)window.V4Twin.setConnected(profile);}
function apply(name){scenario=name;automatic=false;nominal();useProfile(profiles.full);if(name==="full-system")Object.assign(demo,{state:"BEREIT",temperature:23.8,power:0,fan_rpm:0,fan_percent:0,start_allowed:true,start_block_reason:"Alle Freigaben bestätigt"});
 else if(name==="minimal-system"){useProfile(profiles.minimal);Object.assign(demo,{state:"BEREIT",temperature:23.8,power:0,fan_rpm:0,fan_percent:0,temp2_ok:null,current2_ok:null,light_ok:null,start_allowed:true,start_block_reason:"Alle erforderlichen Freigaben bestätigt"});}
 else if(name==="partial-hardware"){useProfile(profiles.partial);Object.assign(demo,{state:"BEREIT",temperature:25.6,power:0,fan_rpm:0,fan_percent:0,temp2_ok:null,current2_ok:null,light_ok:null,start_allowed:true,start_block_reason:"Optionale Hardware nicht angeschlossen"});}
 else if(name==="no-sensors"){useProfile(profiles.noSensors);Object.assign(demo,{state:"AUS",temperature:NaN,temperature1:NaN,temperature2:NaN,power:0,fan_rpm:0,fan_percent:0,sensor_ok:null,temp1_ok:null,temp2_ok:null,current_ok:null,current1_ok:null,current2_ok:null,tla2024_ok:null,light_ok:null,cup:null,start_allowed:false,start_block_reason:"Keine Sensorik angeschlossen"});}
 else if(name==="ready")Object.assign(demo,{state:"BEREIT",temperature:23.8,power:0,fan_rpm:0,fan_percent:0,start_allowed:true,start_block_reason:"Alle Freigaben bestätigt"});
 else if(name==="heating")Object.assign(demo,{state:"AUFHEIZEN",temperature:32.4,power:68,start_allowed:false,start_block_reason:"Heizvorgang bereits aktiv"});
 else if(name==="holding")Object.assign(demo,{state:"HALTEN",temperature:44.9,power:23,start_allowed:false,start_block_reason:"Halteregelung aktiv"});
 else if(name==="error")Object.assign(demo,{state:"FEHLER",fault:"UEBERTEMPERATUR",fault_description:"Maximale sichere Temperatur überschritten",temperature:65.3,power:0,start_allowed:false,start_block_reason:"Fehler quittieren und Ursache prüfen"});
 else if(name==="offline")Object.assign(demo,{power:0,wifi:false,webserver_ready:false,start_allowed:false,start_block_reason:"Keine Live-Verbindung"});
 else if(name==="reconnect")Object.assign(demo,{state:"BEREIT",temperature:29.1,power:0,start_allowed:true,start_block_reason:"Alle Freigaben bestätigt"});
 else if(name==="sensor-error")Object.assign(demo,{state:"FEHLER",fault:"TEMPERATURSENSOR",fault_description:"Temperatursignal fehlt oder ist unplausibel",temperature:NaN,temperature1:NaN,sensor_ok:false,temp1_ok:false,power:0,start_allowed:false,start_block_reason:"Temperatursensor prüfen"});
 else if(name==="fan-error")Object.assign(demo,{state:"FEHLER",fault:"LUEFTER",fault_description:"Kein plausibles Tachosignal bei aktiver Heizleistung",power:0,fan_rpm:0,fan_percent:0,start_allowed:false,start_block_reason:"Lüfter und Tachosignal prüfen"});
 else if(name==="power-error")Object.assign(demo,{state:"FEHLER",fault:"VERSORGUNG",fault_description:"12-V-Leistungsversorgung nicht freigegeben",power:0,power_good:false,start_allowed:false,start_block_reason:"Leistungsversorgung prüfen"});
 else if(name==="demo30"){Object.assign(demo,{state:"HALTEN",temperature:49.5,power:19,setpoint:50,start_allowed:false,start_block_reason:"Halteregelung aktiv"});automatic=true;simMinutes=30;window.V3UI.history.splice(0);prefillThirtyMinutes();}
 derived();document.querySelectorAll("[data-scenario]").forEach(function(button){button.classList.toggle("active",button.dataset.scenario===name);});window.V3UI.acceptStatus(demo,name!=="offline");}
function historyPoint(time,temperature,target,power){return{time:time,temperature:temperature,temperature2:temperature-.6,target:target,power:power,current1:power*.0412,current2:power*.0397,fan:power?760+Math.max(35,power*.82)*19.5:0,light:.72,valid:true,valid2:true,validTarget:true,validPower:true,validCurrent1:true,validCurrent2:true,validFan:true,validLight:true};}
function prefill(){if(window.V3UI.history.length)return;var now=Date.now();for(var seconds=300;seconds>=0;seconds-=2){var progress=(300-seconds)/300,temperature=23.2+9.2*progress+Math.sin(progress*12)*.06,power=88-20*progress;window.V3UI.history.push(historyPoint(now-seconds*1000,temperature,45,power));}window.V3UI.scheduleChart();}
function prefillThirtyMinutes(){var now=Date.now();for(var seconds=1800;seconds>=0;seconds-=5){var minute=(1800-seconds)/60,temperature=22+28.15*(1-Math.exp(-minute/7.5)),error=50-temperature,power=minute<2?100:Math.max(19,Math.min(100,error*4.8+16)),point=historyPoint(now-seconds*1000,temperature,50,power);point.temperature2=temperature-.65+Math.sin(minute)*.05;window.V3UI.history.push(point);}window.V3UI.runtime.range=900;window.V3UI.scheduleChart();}
function tick(now){var dt=Math.min(1,(now-last)/1000);last=now;if(automatic){simMinutes+=dt*1.35;demo.temperature=22+28.05*(1-Math.exp(-simMinutes/7.4));demo.error=demo.setpoint-demo.temperature;demo.power=simMinutes<1.2?100:Math.max(18,Math.min(100,demo.error*4.8+16));demo.state=Math.abs(demo.error)<.35?"HALTEN":"AUFHEIZEN";}else if(scenario==="heating"){demo.temperature+=dt*.014;demo.power=Math.max(25,68-(demo.temperature-32.4)*2.4);}else if(scenario==="holding"){demo.temperature=44.9+Math.sin(now/3000)*.06;demo.power=23+Math.sin(now/2400)*1.5;}derived();if(window.V3UI)window.V3UI.acceptStatus(demo,scenario!=="offline");requestAnimationFrame(tick);}
function unlock(pin){return pin==="1234"?{ok:true,token:"preview-session",expires_in_ms:300000}:{ok:false,reason:"PIN falsch"};}
function command(path,token){if(path!=="stop"&&token!=="preview-session")return;if(path==="start"){scenario="heating";automatic=true;simMinutes=Math.max(0,(demo.temperature-22)/2);demo.state="AUFHEIZEN";demo.power=92;demo.start_allowed=false;demo.start_block_reason="Heizvorgang bereits aktiv";}else if(path==="stop"){scenario="ready";automatic=false;demo.state="BEREIT";demo.power=0;demo.start_allowed=true;demo.start_block_reason="Alle Freigaben bestätigt";}else if(path.indexOf("setpoint?value=")===0){demo.setpoint=Math.max(20,Math.min(60,Number(decodeURIComponent(path.split("=")[1]))||45));}derived();window.V3UI.acceptStatus(demo,true);}
function start(){document.querySelectorAll("[data-scenario]").forEach(function(button){button.addEventListener("click",function(){apply(button.dataset.scenario);});});prefill();var requested=new URLSearchParams(location.search).get("scenario");apply(requested&&document.querySelector('[data-scenario="'+CSS.escape(requested)+'"]')?requested:"heating");requestAnimationFrame(function(now){last=now;tick(now);});}
window.PreviewDriver={start:start,command:command,unlock:unlock,apply:apply};
})();
