(function(){
"use strict";
var base={state:"AUFHEIZEN",fault:"KEIN FEHLER",fault_description:"Keine aktive Störung",temperature:32.4,temperature1:32.4,temperature2:31.8,setpoint:45,error:12.6,power:68,thermal_mode:"HEIZEN",fan_rpm:1850,fan_percent:64,current1:2.8,current2:2.7,supply_voltage:12,light_level:.72,sensor_ok:true,temp1_ok:true,temp2_ok:true,current_ok:true,current1_ok:true,current2_ok:true,tla2024_ok:true,light_ok:true,display_initialized:true,leds_initialized:true,cup:true,power_good:true,wifi:true,webserver_ready:true,wifi_ssid:"Obi W-lan Kenobi",wifi_ip:"10.78.252.72",night:false,start_allowed:false,start_block_reason:"Temperaturregelung bereits aktiv",kp:5.2,ki:.075,p_term:65.5,i_term:2.5,output_limited:false,anti_windup:true,control_period_ms:250,min_safe_temperature:18,max_safe_temperature:65,max_cooling_power:20,uptime_ms:438000};
var demo=Object.assign({},base),scenario="heating",automatic=false,started=performance.now(),last=started,simMinutes=0,simStartTemperature=22,simDirection=1,viewportOpener=null;
var profiles={
 full:["cup","temp1","temp2","plate","peltier1","peltier2","fan","pico","adc","current1","current2","light","oled","rgb","leds","buttons","power","wifi","webserver"],
 minimal:["cup","temp1","plate","peltier1","fan","pico","oled","buttons","power","wifi","webserver"],
 partial:["cup","temp1","plate","peltier1","peltier2","fan","pico","adc","current1","oled","leds","buttons","power","wifi","webserver"],
 noSensors:["plate","peltier1","peltier2","fan","pico","oled","rgb","leds","buttons","power","wifi","webserver"]
};
function derived(){var magnitude=Math.abs(demo.power);demo.error=demo.setpoint-demo.temperature;demo.temperature1=demo.temperature;demo.temperature2=demo.temperature-.6+Math.sin(performance.now()/4500)*.08;demo.thermal_mode=demo.power<0?"KUEHLEN":demo.power>0?"HEIZEN":"AUS";demo.fan_percent=magnitude>0?Math.max(35,Math.round(magnitude*.82)):0;demo.fan_rpm=demo.fan_percent?Math.round(760+demo.fan_percent*19.5):0;demo.current1=magnitude*.0412;demo.current2=magnitude*.0397;demo.p_term=demo.error*demo.kp;demo.i_term=demo.power-demo.p_term;demo.uptime_ms+=500;}
function nominal(){Object.assign(demo,base,{fault:"KEIN FEHLER",fault_description:"Keine aktive Störung",sensor_ok:true,temp1_ok:true,temp2_ok:true,current_ok:true,current1_ok:true,current2_ok:true,tla2024_ok:true,cup:true,power_good:true,wifi:true,webserver_ready:true});}
function useProfile(profile){if(window.V4Twin&&window.V4Twin.setConnected)window.V4Twin.setConnected(profile);}
function apply(name){scenario=name;automatic=false;nominal();useProfile(profiles.full);if(name==="full-system")Object.assign(demo,{state:"BEREIT",temperature:23.8,power:0,fan_rpm:0,fan_percent:0,start_allowed:true,start_block_reason:"Alle Freigaben bestätigt"});
 else if(name==="minimal-system"){useProfile(profiles.minimal);Object.assign(demo,{state:"BEREIT",temperature:23.8,power:0,fan_rpm:0,fan_percent:0,temp2_ok:null,current2_ok:null,light_ok:null,start_allowed:true,start_block_reason:"Alle erforderlichen Freigaben bestätigt"});}
 else if(name==="partial-hardware"){useProfile(profiles.partial);Object.assign(demo,{state:"BEREIT",temperature:25.6,power:0,fan_rpm:0,fan_percent:0,temp2_ok:null,current2_ok:null,light_ok:null,start_allowed:true,start_block_reason:"Optionale Hardware nicht angeschlossen"});}
 else if(name==="no-sensors"){useProfile(profiles.noSensors);Object.assign(demo,{state:"AUS",temperature:NaN,temperature1:NaN,temperature2:NaN,power:0,fan_rpm:0,fan_percent:0,sensor_ok:null,temp1_ok:null,temp2_ok:null,current_ok:null,current1_ok:null,current2_ok:null,tla2024_ok:null,light_ok:null,cup:null,start_allowed:false,start_block_reason:"Keine Sensorik angeschlossen"});}
 else if(name==="ready")Object.assign(demo,{state:"BEREIT",temperature:23.8,power:0,fan_rpm:0,fan_percent:0,start_allowed:true,start_block_reason:"Alle Freigaben bestätigt"});
 else if(name==="heating")Object.assign(demo,{state:"AUFHEIZEN",temperature:32.4,power:68,start_allowed:false,start_block_reason:"Heizvorgang bereits aktiv"});
 else if(name==="cooling"){Object.assign(demo,{state:"KUEHLEN",temperature:32.4,setpoint:20,power:-20,start_allowed:false,start_block_reason:"Kühlvorgang bereits aktiv"});window.V3UI.history.splice(0);prefillCooling();}
 else if(name==="holding")Object.assign(demo,{state:"HALTEN",temperature:44.9,power:23,start_allowed:false,start_block_reason:"Halteregelung aktiv"});
 else if(name==="error")Object.assign(demo,{state:"FEHLER",fault:"UEBERTEMPERATUR",fault_description:"Maximale sichere Temperatur überschritten",temperature:65.3,power:0,start_allowed:false,start_block_reason:"Fehler quittieren und Ursache prüfen"});
 else if(name==="offline"||name==="disconnect")Object.assign(demo,{wifi:false,webserver_ready:false,start_allowed:false,start_block_reason:"Keine Live-Verbindung"});
 else if(name==="reconnect"||name==="recovery")Object.assign(demo,{state:"BEREIT",temperature:29.1,power:0,start_allowed:true,start_block_reason:"Alle Freigaben bestätigt"});
 else if(name==="sensor-error")Object.assign(demo,{state:"FEHLER",fault:"TEMPERATURSENSOR",fault_description:"Temperatursignal fehlt oder ist unplausibel",temperature:NaN,temperature1:NaN,sensor_ok:false,temp1_ok:false,power:0,start_allowed:false,start_block_reason:"Temperatursensor prüfen"});
 else if(name==="fan-error")Object.assign(demo,{state:"FEHLER",fault:"LUEFTER",fault_description:"Kein plausibles Tachosignal bei aktiver Peltierleistung",power:0,fan_rpm:0,fan_percent:0,start_allowed:false,start_block_reason:"Lüfter und Tachosignal prüfen"});
 else if(name==="power-error")Object.assign(demo,{state:"FEHLER",fault:"VERSORGUNG",fault_description:"12-V-Leistungsversorgung nicht freigegeben",power:0,power_good:false,start_allowed:false,start_block_reason:"Leistungsversorgung prüfen"});
 else if(name==="demo30"){Object.assign(demo,{state:"HALTEN",temperature:49.5,power:19,setpoint:50,start_allowed:false,start_block_reason:"Halteregelung aktiv"});automatic=true;simMinutes=30;simStartTemperature=22;simDirection=1;window.V3UI.history.splice(0);prefillThirtyMinutes();}
 derived();document.querySelectorAll("[data-scenario]").forEach(function(button){button.classList.toggle("active",button.dataset.scenario===name);});window.V3UI.acceptStatus(demo,name!=="offline"&&name!=="disconnect");}
function historyPoint(time,temperature,target,power){var error=target-temperature,pTerm=error*base.kp,iTerm=power-pTerm,magnitude=Math.abs(power);return{time:time,temperature:temperature,temperature2:temperature-.6,target:target,power:power,error:error,pTerm:pTerm,iTerm:iTerm,rawOutput:pTerm+iTerm,current1:magnitude*.0412,current2:magnitude*.0397,fan:magnitude?760+Math.max(35,magnitude*.82)*19.5:0,light:.72,valid:true,valid2:true,validTarget:true,validPower:true,validController:true,validCurrent1:true,validCurrent2:true,validFan:true,validLight:true};}
function prefill(){if(window.V3UI.history.length)return;var now=Date.now();for(var seconds=300;seconds>=0;seconds-=2){var progress=(300-seconds)/300,temperature=23.2+9.2*progress+Math.sin(progress*12)*.06,power=88-20*progress;window.V3UI.history.push(historyPoint(now-seconds*1000,temperature,45,power));}window.V3UI.scheduleChart();}
function prefillCooling(){var now=Date.now();for(var seconds=300;seconds>=0;seconds-=2){var progress=(300-seconds)/300,temperature=38-5.6*progress+Math.sin(progress*10)*.04,power=-20+2*progress;window.V3UI.history.push(historyPoint(now-seconds*1000,temperature,20,power));}window.V3UI.scheduleChart();}
function prefillThirtyMinutes(){var now=Date.now();for(var seconds=1800;seconds>=0;seconds-=5){var minute=(1800-seconds)/60,temperature=22+28.15*(1-Math.exp(-minute/7.5)),error=50-temperature,power=minute<2?100:Math.max(19,Math.min(100,error*4.8+16)),point=historyPoint(now-seconds*1000,temperature,50,power);point.temperature2=temperature-.65+Math.sin(minute)*.05;window.V3UI.history.push(point);}window.V3UI.runtime.range=900;window.V3UI.scheduleChart();}
function tick(now){var dt=Math.min(1,(now-last)/1000);last=now;if(automatic){simMinutes+=dt*1.35;var change=demo.setpoint-simStartTemperature;demo.temperature=simStartTemperature+change*(1-Math.exp(-simMinutes/7.4));demo.error=demo.setpoint-demo.temperature;var maximum=simDirection<0?20:100,minimum=simDirection<0?4:18,magnitude=simMinutes<1.2?maximum:Math.max(minimum,Math.min(maximum,Math.abs(demo.error)*4.8+minimum));demo.power=simDirection*magnitude;demo.state=Math.abs(demo.error)<=.35?"HALTEN":simDirection<0?"KUEHLEN":"AUFHEIZEN";}else if(scenario==="heating"){demo.temperature+=dt*.014;demo.power=Math.max(25,68-(demo.temperature-32.4)*2.4);}else if(scenario==="cooling"){demo.temperature-=dt*.01;demo.power=-Math.max(6,20-(32.4-demo.temperature)*2.2);}else if(scenario==="holding"){demo.temperature=44.9+Math.sin(now/3000)*.06;demo.power=23+Math.sin(now/2400)*1.5;}derived();if(window.V3UI&&(!tick.lastUi||now-tick.lastUi>=100)){tick.lastUi=now;window.V3UI.acceptStatus(demo,scenario!=="offline"&&scenario!=="disconnect");}requestAnimationFrame(tick);}
function unlock(pin){return pin===""||pin==="1234"?{ok:true,token:"preview-session",expires_in_ms:300000}:{ok:false,reason:"PIN falsch"};}
function setCup(present){demo.cup=!!present;if(!demo.cup){demo.start_allowed=false;demo.start_block_reason="Kein Becher erkannt";}else if(demo.state==="BEREIT"&&demo.sensor_ok&&demo.current_ok&&demo.power_good){demo.start_allowed=true;demo.start_block_reason="Alle Freigaben bestätigt";}derived();window.V3UI.acceptStatus(demo,true);}
function command(path,token){if(path!=="stop"&&token!=="preview-session")return false;if(path==="start"){simDirection=demo.setpoint<demo.temperature?-1:1;scenario=simDirection<0?"cooling":"heating";automatic=true;simMinutes=0;simStartTemperature=demo.temperature;demo.state=simDirection<0?"KUEHLEN":"AUFHEIZEN";demo.power=simDirection*(simDirection<0?20:92);demo.start_allowed=false;demo.start_block_reason=simDirection<0?"Kühlvorgang bereits aktiv":"Heizvorgang bereits aktiv";if(simDirection<0){window.V3UI.history.splice(0);prefillCooling();}}else if(path==="stop"){scenario="ready";automatic=false;demo.state="BEREIT";demo.power=0;demo.start_allowed=true;demo.start_block_reason="Alle Freigaben bestätigt";}else if(path.indexOf("setpoint?value=")===0){demo.setpoint=Math.max(20,Math.min(60,Number(decodeURIComponent(path.split("=")[1]))||45));}else return false;derived();window.V3UI.acceptStatus(demo,true);return true;}
function setupViewportPreview(){
 var parameters=new URLSearchParams(location.search);if(parameters.get("frame")==="1"){document.body.classList.add("preview-frame");return;}
 var dialog=document.querySelector(".preview-viewport-dialog"),stage=document.querySelector(".preview-viewport-stage"),shell=document.querySelector(".preview-device-frame"),frame=document.querySelector(".preview-viewport-frame"),title=document.querySelector(".preview-viewport-title"),close=document.querySelector(".preview-viewport-close"),activeMode="desktop",sizes={desktop:{width:1440,height:900,label:"PC-ANSICHT · 1440 × 900"},mobile:{width:390,height:844,label:"HANDY-ANSICHT · 390 × 844"}};
 if(!dialog||!stage||!shell||!frame)return;
 function fit(){var size=sizes[activeMode],border=activeMode==="mobile"?14:0,scale=Math.min(1,(stage.clientWidth-32)/(size.width+border),(stage.clientHeight-32)/(size.height+border));scale=Math.max(.2,scale);shell.classList.toggle("mobile",activeMode==="mobile");shell.style.width=Math.round(size.width*scale+border)+"px";shell.style.height=Math.round(size.height*scale+border)+"px";frame.style.width=size.width+"px";frame.style.height=size.height+"px";frame.style.transform="scale("+scale+")";}
 function open(mode){activeMode=sizes[mode]?mode:"desktop";var size=sizes[activeMode],url=new URL(location.href);url.searchParams.delete("view");url.searchParams.set("frame","1");url.searchParams.set("scenario",scenario);title.textContent=size.label;document.querySelectorAll("[data-preview-viewport]").forEach(function(button){var active=button.dataset.previewViewport===activeMode;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));});frame.src=url.href;if(!dialog.open)dialog.showModal();requestAnimationFrame(fit);}
 viewportOpener=open;
 document.querySelectorAll("[data-preview-viewport]").forEach(function(button){button.addEventListener("click",function(){open(button.dataset.previewViewport);});});
 close.addEventListener("click",function(){dialog.close();});dialog.addEventListener("close",function(){frame.src="about:blank";});addEventListener("resize",function(){if(dialog.open)fit();},{passive:true});
 var requestedView=parameters.get("view");if(sizes[requestedView])setTimeout(function(){open(requestedView);},180);
}
function start(){
 var toggle=document.querySelector(".preview-tools-toggle"),deck=document.querySelector(".preview-deck");function setTools(open){if(!toggle||!deck)return;deck.hidden=!open;toggle.setAttribute("aria-expanded",String(open));}if(toggle)toggle.addEventListener("click",function(){setTools(deck.hidden);});addEventListener("keydown",function(event){if(event.altKey&&event.key.toLowerCase()==="d"){event.preventDefault();setTools(!deck.hidden);}});document.querySelectorAll("[data-scenario]").forEach(function(button){button.addEventListener("click",function(){apply(button.dataset.scenario);});});setupViewportPreview();prefill();var parameters=new URLSearchParams(location.search),requested=parameters.get("scenario");requested=requested&&document.querySelector('[data-scenario="'+CSS.escape(requested)+'"]')?requested:"heating";if(requested==="disconnect"){apply("heating");setTimeout(function(){apply("disconnect");},80);}else if(requested==="recovery"){apply("heating");apply("disconnect");setTimeout(function(){apply("recovery");},120);}else apply(requested);if(parameters.get("cup")==="absent")setCup(false);requestAnimationFrame(function(now){last=now;tick(now);});
}
window.PreviewDriver={start:start,command:command,unlock:unlock,apply:apply,setCup:setCup,openViewport:function(mode){if(viewportOpener)viewportOpener(mode);}};
})();
