#pragma once

static const char dashboard_html[] =
"<!doctype html><html lang='de'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Becherhalter Regelkreis</title><style>"
":root{--bg:#08101e;--panel:#111c2f;--line:#283851;--text:#ecf4ff;--muted:#8ea3bd;--heat:#ff7145;--good:#4de3a1;--blue:#55b8ff}"
"*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#172943,var(--bg) 42%);color:var(--text);font:15px system-ui,sans-serif}"
"main{max-width:1180px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}h1{font-size:clamp(22px,4vw,36px);margin:0}.sub{color:var(--muted)}"
".badge{padding:8px 14px;border:1px solid var(--line);border-radius:99px;background:#0a1424}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}"
".card,.panel{background:linear-gradient(145deg,#142238,#0d1728);border:1px solid var(--line);border-radius:16px;padding:17px;box-shadow:0 14px 45px #0004}.label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.12em}.value{font-size:27px;font-weight:700;margin-top:6px}"
".layout{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.panel h2{margin:0 0 14px;font-size:17px}.loop{display:grid;grid-template-columns:repeat(5,1fr);align-items:center;gap:7px;position:relative;padding-bottom:42px}.block{border:1px solid #355273;border-radius:12px;min-height:91px;padding:12px;text-align:center;background:#102039}.block b{display:block;margin:7px 0;font-size:18px}.arrow{text-align:center;color:var(--blue);font-size:24px}.feedback{position:absolute;left:8%;right:8%;bottom:5px;border:2px solid var(--blue);border-top:0;height:26px;border-radius:0 0 12px 12px;color:var(--blue);text-align:center;font-size:11px;padding-top:8px}.feedback:before{content:'\2191';position:absolute;left:-6px;top:-11px;font-size:20px}"
"canvas{width:100%;height:260px;background:#091425;border-radius:10px}.controls{display:flex;gap:9px;flex-wrap:wrap}.controls input{width:110px;background:#091425;color:white;border:1px solid var(--line);padding:11px;border-radius:9px}.controls button{border:0;border-radius:9px;padding:11px 18px;font-weight:700;cursor:pointer}.start{background:var(--good)}.stop{background:#ff5b63;color:white}.set{background:var(--blue)}"
".details{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:17px}.details div{background:#091425;border-radius:9px;padding:10px}.details span{display:block;color:var(--muted);font-size:11px}.error{color:#ff6d75}.ok{color:var(--good)}"
"@media(max-width:800px){main{padding:14px}.grid{grid-template-columns:1fr 1fr}.layout{grid-template-columns:1fr}.loop{grid-template-columns:1fr}.arrow{transform:rotate(90deg)}.feedback{display:none}.top{align-items:flex-start;flex-direction:column}}"
"</style></head><body><main><div class='top'><div><h1>Becherhalter</h1><div class='sub'>Geschlossener Temperaturregelkreis</div></div><div class='badge' id='state'>VERBINDUNG...</div></div>"
"<section class='grid'><div class='card'><div class='label'>Isttemperatur</div><div class='value' id='temp'>--.- °C</div></div><div class='card'><div class='label'>Solltemperatur</div><div class='value' id='setpoint'>--.- °C</div></div><div class='card'><div class='label'>Regelabweichung</div><div class='value' id='error'>--.- °C</div></div><div class='card'><div class='label'>Peltier-Leistung</div><div class='value' id='power'>-- %</div></div></section>"
"<section class='panel'><h2>Regelkreis · Live-Werte</h2><div class='loop'><div class='block'><span>Sollwert</span><b id='bset'>-- °C</b></div><div class='arrow'>→</div><div class='block'><span>PI-Regler</span><b id='berr'>e = -- °C</b></div><div class='arrow'>→</div><div class='block'><span>Peltier 1 + 2</span><b id='bpwr'>-- %</b></div><div class='arrow'>→</div><div class='block'><span>Heizstrecke</span><b>Becher</b></div><div class='arrow'>→</div><div class='block'><span>TMP36 Sensoren</span><b id='btemp'>-- °C</b></div><div class='feedback'>Rückführung der Isttemperatur</div></div></section>"
"<section class='layout' style='margin-top:14px'><div class='panel'><h2>Temperaturverlauf</h2><canvas id='chart' width='760' height='260'></canvas></div><div class='panel'><h2>Bedienung</h2><div class='controls'><input id='target' type='number' min='20' max='60' step='.5' value='45'><button class='set' onclick='setTarget()'>SETZEN</button><button class='start' onclick=\"act('start')\">START</button><button class='stop' onclick=\"act('stop')\">STOP</button></div><div class='details'><div><span>Fan</span><b id='fan'>-- rpm</b></div><div><span>Strom P1 / P2</span><b id='current'>-- / -- A</b></div><div><span>Sensorstatus</span><b id='sensor'>--</b></div><div><span>Systemstatus</span><b id='system'>--</b></div><div><span>WLAN</span><b id='wifi'>--</b></div><div><span>Umgebung</span><b id='light'>--</b></div></div></div></section>"
"</main><script>const hist=[];async function act(a){await fetch('/api/'+a,{method:'POST'});await update()}async function setTarget(){let v=document.getElementById('target').value;await fetch('/api/setpoint?value='+encodeURIComponent(v),{method:'POST'});await update()}"
"function val(id,v){document.getElementById(id).textContent=v}function draw(){const c=document.getElementById('chart'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#223651';x.lineWidth=1;for(let t=0;t<5;t++){let y=15+t*(h-30)/4;x.beginPath();x.moveTo(35,y);x.lineTo(w-8,y);x.stroke()}function line(key,color,min,max){x.strokeStyle=color;x.lineWidth=2;x.beginPath();hist.forEach((p,i)=>{let px=35+i*(w-45)/119,py=h-15-(p[key]-min)*(h-30)/(max-min);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}line('sp','#55b8ff',15,70);line('t','#4de3a1',15,70);line('p','#ff7145',0,100);x.fillStyle='#8ea3bd';x.font='11px system-ui';x.fillText('Temperatur °C / Leistung %',38,12)}"
"async function update(){try{let r=await fetch('/api/status',{cache:'no-store'}),s=await r.json();val('state',s.state);val('temp',s.temperature.toFixed(1)+' °C');val('setpoint',s.setpoint.toFixed(1)+' °C');val('error',s.error.toFixed(1)+' °C');val('power',s.power.toFixed(0)+' %');val('bset',s.setpoint.toFixed(1)+' °C');val('berr','e = '+s.error.toFixed(1)+' °C');val('bpwr',s.power.toFixed(0)+' %');val('btemp',s.temperature.toFixed(1)+' °C');val('fan',s.fan_rpm+' rpm');val('current',s.current1.toFixed(2)+' / '+s.current2.toFixed(2)+' A');val('sensor',s.sensor_ok?'OK':'FEHLER');val('system',s.fault==='KEIN FEHLER'?'OK':s.fault);val('wifi',s.wifi?'VERBUNDEN':'OFFLINE');val('light',s.night?'NACHTMODUS':'TAGMODUS');document.getElementById('system').className=s.fault==='KEIN FEHLER'?'ok':'error';hist.push({t:s.temperature,sp:s.setpoint,p:s.power});if(hist.length>120)hist.shift();draw()}catch(e){val('state','OFFLINE')}}setInterval(update,500);update();</script></body></html>";

