#!/usr/bin/env python3
"""Build the readable local preview and the single-file Pico dashboard asset."""

from __future__ import annotations

import argparse
import gzip
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ui-v3" / "src"
V4_SOURCE = ROOT / "ui-v4" / "src"
PREVIEW = ROOT / "preview.html"
PRODUCTION = ROOT / "ui" / "dist" / "dashboard.production.html"
HEADER = ROOT / "include" / "web_assets.h"
STATS = ROOT / "ui" / "dist" / "build-stats.json"

PREVIEW_CONTROLS = """
<div class="preview-deck" aria-label="Lokale Vorschau-Szenarien">
 <button type="button" data-scenario="ready">READY</button>
 <button type="button" data-scenario="heating" class="active">HEATING</button>
 <button type="button" data-scenario="holding">HOLDING</button>
 <button type="button" data-scenario="error">ERROR</button>
 <button type="button" data-scenario="offline">OFFLINE</button>
 <button type="button" data-scenario="reconnect">RECONNECT</button>
 <button type="button" data-scenario="sensor-error">SENSOR ERROR</button>
 <button type="button" data-scenario="fan-error">FAN ERROR</button>
 <button type="button" data-scenario="power-error">POWER ERROR</button>
 <button type="button" data-scenario="demo30">30 MIN DEMO</button>
</div>
""".strip()


def read(name: str) -> str:
    return (SOURCE / name).read_text(encoding="utf-8")


def read_v4(name: str) -> str:
    return (V4_SOURCE / name).read_text(encoding="utf-8")


def minify_css(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    source = re.sub(r"\s+", " ", source)
    source = re.sub(r"\s*([{}:;,>])\s*", r"\1", source)
    source = re.sub(r";}", "}", source)
    return source.strip()


def minify_javascript(source: str) -> str:
    # This conservative pass preserves string/template literal semantics. It removes
    # comments and indentation while leaving statement newlines intact.
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    lines = []
    for line in source.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("//"):
            lines.append(stripped)
    return "\n".join(lines)


def compose(*, preview: bool, minified: bool) -> tuple[str, str, str]:
    template = read("index.html")
    css = "\n\n".join([read("experience.css"), read_v4("digital-twin.css")])
    scripts = [read("product-scene.js"), read("thermal-overlay.js"), read_v4("component-model.js"), read_v4("digital-twin.js")]
    if preview:
        scripts.append(read("preview.js"))
    scripts.append(read("experience.js").replace("__PREVIEW_MODE__", "true" if preview else "false"))
    javascript = "\n\n".join(scripts)
    if minified:
        css = minify_css(css)
        javascript = minify_javascript(javascript)
    html = template.replace("/*__CSS__*/", css)
    html = html.replace("<!--__PREVIEW_CONTROLS__-->", PREVIEW_CONTROLS if preview else "")
    html = html.replace("/*__SCRIPT__*/", javascript)
    if minified:
        html = re.sub(r">\s+<", "><", html).strip() + "\n"
    return html, css, javascript


def c_header(html: str) -> str:
    fragments = html.splitlines(keepends=True)
    literals = "\n".join(json.dumps(fragment, ensure_ascii=False) for fragment in fragments)
    return (
        "#pragma once\n\n"
        "/* Generated by tools/build_ui.py. Edit files under ui-v3/src and ui-v4/src. */\n"
        "static const char dashboard_html[] =\n"
        f"{literals}\n;\n"
    )


def build_stats(preview_html: str, production_html: str, css: str, javascript: str) -> dict:
    size = lambda value: len(value.encode("utf-8"))
    compressed = lambda value: len(gzip.compress(value.encode("utf-8"), compresslevel=9, mtime=0))
    return {
        "preview_bytes": size(preview_html),
        "production_bytes": size(production_html),
        "production_gzip_bytes_theoretical": compressed(production_html),
        "production_css_bytes": size(css),
        "production_javascript_bytes": size(javascript),
        "external_library_bytes": 0,
        "runtime_http_requests_for_assets": 0,
        "webgl_draw_calls_per_frame": 1,
        "preview_product_scene_frame_cap_fps": 60,
        "preview_thermal_overlay_frame_cap_fps": 60,
        "embedded_product_scene_frame_cap_fps": 30,
        "embedded_thermal_overlay_frame_cap_fps": 30,
        "history_max_seconds": 1800,
    }


def write_or_check(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated assets differ")
    args = parser.parse_args()
    preview_html, _, _ = compose(preview=True, minified=False)
    production_html, production_css, production_js = compose(preview=False, minified=True)
    stats = build_stats(preview_html, production_html, production_css, production_js)
    outputs = {
        PREVIEW: preview_html,
        PRODUCTION: production_html,
        HEADER: c_header(production_html),
        STATS: json.dumps(stats, indent=2, sort_keys=True) + "\n",
    }
    current = all(write_or_check(path, content, args.check) for path, content in outputs.items())
    print(
        "UI build: "
        f"preview={stats['preview_bytes']} B, "
        f"production={stats['production_bytes']} B, "
        f"gzip~{stats['production_gzip_bytes_theoretical']} B, "
        f"libraries={stats['external_library_bytes']} B"
    )
    return 0 if current else 1


if __name__ == "__main__":
    raise SystemExit(main())
